[32mINFO    [0m integration.helpers:helpers.py:367 Calling: GET -- https://10.169.42.219:9200/_cluster/state/cluster_manager_node
[32mINFO    [0m integration.helpers:helpers.py:367 Calling: GET -- https://10.169.42.219:9200/_nodes
[32mINFO    [0m integration.helpers:helpers.py:367 Calling: GET -- https://10.169.42.219:9200/
[32mINFO    [0m integration.ha.test_ha_networking:test_ha_networking.py:114 Network cut from unit: 2
[32mINFO    [0m integration.helpers:helpers.py:367 Calling: GET -- https://10.169.42.219:9200/
[32mINFO    [0m integration.helpers:helpers.py:367 Calling: GET -- https://10.169.42.219:9200/
[32mINFO    [0m integration.helpers:helpers.py:367 Calling: GET -- https://10.169.42.219:9200/
[32mINFO    [0m integration.helpers:helpers.py:367 Calling: GET -- https://10.169.42.201:9200/_cluster/state/cluster_manager_node
[32mINFO    [0m integration.helpers:helpers.py:367 Calling: GET -- https://10.169.42.201:9200/_nodes
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:329 



[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:330 Model  Controller           Cloud/Region         Version  SLA          Timestamp
test   localhost-localhost  localhost/localhost  3.5.3    unsupported  03:20:16Z

App                       Version  Status  Scale  Charm                     Channel        Rev  Exposed  Message
opensearch                         active    2/3  opensearch                                 0  no       
self-signed-certificates           active      1  self-signed-certificates  latest/stable  155  no       

Unit                         Workload  Agent  Machine  Public address  Ports     Message
opensearch/0                 active    idle   1        10.169.42.157   9200/tcp  
opensearch/1*                active    idle   2        10.169.42.201   9200/tcp  
opensearch/2                 unknown   lost   3        10.169.42.219   9200/tcp  agent lost, see 'juju show-status-log opensearch/2'
self-signed-certificates/0*  active    idle   0        10.169.42.71              

Machine  State    Address        Inst id        Base          AZ  Message
0        started  10.169.42.71   juju-f3cfb9-0  ubuntu@22.04      Running
1        started  10.169.42.157  juju-f3cfb9-1  ubuntu@22.04      Running
2        started  10.169.42.201  juju-f3cfb9-2  ubuntu@22.04      Running
3        down     10.169.42.219  juju-f3cfb9-3  ubuntu@22.04      Running

[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:337 


03:20:16 -- Waiting for model...
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:277 	App: opensearch - Units - conditions unmet.
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:278 
	app: opensearch active -- message: None
		opensearch-0.fe2  -- (10.169.42.157) -- [idle (since: 03:20:11)] active: 
		opensearch-1.fe2* -- (10.169.42.201) -- [idle (since: 03:19:50)] active: 
		opensearch-2.fe2  -- (10.169.42.219) -- [lost (since: 03:13:20)] unknown: agent lost, see 'juju show-status-log opensearch/2'

[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:337 


03:20:46 -- Waiting for model...
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:277 	App: opensearch - Units - conditions unmet.
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:278 
	app: opensearch active -- message: None
		opensearch-0.fe2  -- (10.169.42.157) -- [idle (since: 03:20:11)] active: 
		opensearch-1.fe2* -- (10.169.42.201) -- [idle (since: 03:19:50)] active: 
		opensearch-2.fe2  -- (10.169.42.219) -- [executing (since: 03:20:46)] active: 

[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:337 


03:20:58 -- Waiting for model...
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:277 	App: opensearch - Units - conditions unmet.
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:278 
	app: opensearch active -- message: None
		opensearch-0.fe2  -- (10.169.42.157) -- [idle (since: 03:20:56)] active: 
		opensearch-1.fe2* -- (10.169.42.201) -- [idle (since: 03:20:56)] active: 
		opensearch-2.fe2  -- (10.169.42.219) -- [executing (since: 03:20:51)] waiting: The OpenSearch service is stopping.

[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:337 


03:21:10 -- Waiting for model...
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:277 	App: opensearch - Units - conditions unmet.
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:278 
	app: opensearch active -- message: None
		opensearch-0.fe2  -- (10.169.42.157) -- [idle (since: 03:20:56)] active: 
		opensearch-1.fe2* -- (10.169.42.201) -- [idle (since: 03:20:56)] active: 
		opensearch-2.fe2  -- (10.169.42.219) -- [executing (since: 03:20:51)] waiting: Waiting for OpenSearch to start...

[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:337 


03:21:22 -- Waiting for model...
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:277 	App: opensearch - Units - conditions unmet.
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:278 
	app: opensearch active -- message: None
		opensearch-0.fe2  -- (10.169.42.157) -- [idle (since: 03:21:21)] active: 
		opensearch-1.fe2* -- (10.169.42.201) -- [executing (since: 03:21:20)] active: 
		opensearch-2.fe2  -- (10.169.42.219) -- [executing (since: 03:21:21)] active: 

[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:337 


03:21:33 -- Waiting for model...
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:277 	App: opensearch - Units - conditions unmet.
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:278 
	app: opensearch active -- message: None
		opensearch-0.fe2  -- (10.169.42.157) -- [idle (since: 03:21:21)] active: 
		opensearch-1.fe2* -- (10.169.42.201) -- [idle (since: 03:21:22)] active: 
		opensearch-2.fe2  -- (10.169.42.219) -- [idle (since: 03:21:23)] active: 

[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:337 


03:21:45 -- Waiting for model...
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:277 	App: opensearch - Units - conditions unmet.
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:278 
	app: opensearch active -- message: None
		opensearch-0.fe2  -- (10.169.42.157) -- [idle (since: 03:21:21)] active: 
		opensearch-1.fe2* -- (10.169.42.201) -- [idle (since: 03:21:22)] active: 
		opensearch-2.fe2  -- (10.169.42.219) -- [idle (since: 03:21:23)] active: 

[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:337 


03:21:56 -- Waiting for model...
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:277 	App: opensearch - Units - conditions unmet.
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:278 
	app: opensearch active -- message: None
		opensearch-0.fe2  -- (10.169.42.157) -- [idle (since: 03:21:21)] active: 
		opensearch-1.fe2* -- (10.169.42.201) -- [idle (since: 03:21:22)] active: 
		opensearch-2.fe2  -- (10.169.42.219) -- [idle (since: 03:21:23)] active: 

[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:337 


03:22:09 -- Waiting for model...
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:277 	App: opensearch - Units - conditions unmet.
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:278 
	app: opensearch active -- message: None
		opensearch-0.fe2  -- (10.169.42.157) -- [idle (since: 03:21:21)] active: 
		opensearch-1.fe2* -- (10.169.42.201) -- [idle (since: 03:21:22)] active: 
		opensearch-2.fe2  -- (10.169.42.219) -- [idle (since: 03:21:23)] active: 

[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:337 


03:22:20 -- Waiting for model...
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:277 	App: opensearch - Units - conditions unmet.
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:278 
	app: opensearch active -- message: None
		opensearch-0.fe2  -- (10.169.42.157) -- [idle (since: 03:21:21)] active: 
		opensearch-1.fe2* -- (10.169.42.201) -- [idle (since: 03:21:22)] active: 
		opensearch-2.fe2  -- (10.169.42.219) -- [idle (since: 03:21:23)] active: 

[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:337 


03:22:32 -- Waiting for model...
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:277 	App: opensearch - Units - conditions unmet.
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:278 
	app: opensearch active -- message: None
		opensearch-0.fe2  -- (10.169.42.157) -- [idle (since: 03:21:21)] active: 
		opensearch-1.fe2* -- (10.169.42.201) -- [idle (since: 03:21:22)] active: 
		opensearch-2.fe2  -- (10.169.42.219) -- [idle (since: 03:21:23)] active: 

[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:337 


03:22:43 -- Waiting for model...
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:348 03:22:45 -- Waiting for model: complete.



[1m[31mERROR   [0m integration.ha.helpers:helpers.py:409 Network not restored yet, attempting again.
[1m[31mERROR   [0m integration.ha.helpers:helpers.py:409 Network not restored yet, attempting again.
[1m[31mERROR   [0m integration.ha.helpers:helpers.py:409 Network not restored yet, attempting again.
[1m[31mERROR   [0m integration.ha.helpers:helpers.py:409 Network not restored yet, attempting again.
[1m[31mERROR   [0m integration.ha.helpers:helpers.py:409 Network not restored yet, attempting again.
[1m[31mERROR   [0m integration.ha.helpers:helpers.py:409 Network not restored yet, attempting again.
[1m[31mERROR   [0m integration.ha.helpers:helpers.py:409 Network not restored yet, attempting again.
[1m[31mERROR   [0m integration.ha.helpers:helpers.py:409 Network not restored yet, attempting again.
[1m[31mERROR   [0m integration.ha.helpers:helpers.py:409 Network not restored yet, attempting again.
[32mINFO    [0m integration.helpers:helpers.py:367 Calling: GET -- https://10.169.42.54:9200/
[32mINFO    [0m integration.helpers:helpers.py:367 Calling: GET -- https://10.169.42.54:9200/_nodes
[32mINFO    [0m integration.ha.helpers:helpers.py:247 Continuous writes result: namespace(max_stored_id=794, count=795, last_expected_id=794)
[32mINFO    [0m integration.helpers:helpers.py:367 Calling: GET -- https://10.169.42.201:9200/series_index/_search_shards
[32mINFO    [0m integration.ha.conftest:conftest.py:57 



The writes have been cleared.