[32mINFO    [0m integration.ha.test_backups:test_backups.py:796 Syncing credentials for microceph
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  opensearch/0 [executing] maintenance: Backup setup started.
  opensearch/1 [executing] maintenance: Backup setup started.
  opensearch/2 [executing] maintenance: Backup setup started.
  s3-integrator/0 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  opensearch/0 [idle] active: 
  opensearch/1 [executing] active: 
  opensearch/2 [idle] active: 
[32mINFO    [0m integration.helpers:helpers.py:367 Calling: GET -- https://10.249.22.76:9200/_recovery?human
[32mINFO    [0m integration.ha.helpers:helpers.py:247 Continuous writes result: namespace(max_stored_id=195, count=196, last_expected_id=195)
[32mINFO    [0m integration.helpers:helpers.py:367 Calling: GET -- https://10.249.22.76:9200/series_index/_search_shards
[32mINFO    [0m integration.helpers:helpers.py:367 Calling: POST -- https://10.249.22.76:9200/series_index/_refresh
[32mINFO    [0m integration.helpers:helpers.py:367 Calling: GET -- https://10.249.22.76:9200/series_index/_count
[32mINFO    [0m integration.helpers:helpers.py:367 Calling: GET -- https://10.249.22.76:9200/_recovery?human
[32mINFO    [0m integration.helpers:helpers.py:367 Calling: POST -- https://10.249.22.76:9200/series_index/_refresh
[32mINFO    [0m integration.helpers:helpers.py:367 Calling: GET -- https://10.249.22.76:9200/series_index/_count
[32mINFO    [0m integration.ha.helpers:helpers.py:591 Testing restore for series_index - original count pre-restore: 196, and now, new count: 163
[32mINFO    [0m integration.ha.test_backups:test_backups.py:796 Syncing credentials for aws
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  opensearch/0 [executing] maintenance: Backup setup started.
  opensearch/1 [executing] maintenance: Backup setup started.
  opensearch/2 [executing] maintenance: Backup setup started.
  s3-integrator/0 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  opensearch/0 [idle] active: 
  opensearch/1 [idle] active: 
  opensearch/2 [idle] active: 
[32mINFO    [0m integration.helpers:helpers.py:367 Calling: GET -- https://10.249.22.76:9200/_recovery?human
[32mINFO    [0m integration.ha.helpers:helpers.py:247 Continuous writes result: namespace(max_stored_id=188, count=189, last_expected_id=188)
[32mINFO    [0m integration.helpers:helpers.py:367 Calling: GET -- https://10.249.22.76:9200/series_index/_search_shards
[32mINFO    [0m integration.helpers:helpers.py:367 Calling: POST -- https://10.249.22.76:9200/series_index/_refresh
[32mINFO    [0m integration.helpers:helpers.py:367 Calling: GET -- https://10.249.22.76:9200/series_index/_count
[32mINFO    [0m integration.helpers:helpers.py:367 Calling: GET -- https://10.249.22.76:9200/_recovery?human
[32mINFO    [0m integration.helpers:helpers.py:367 Calling: POST -- https://10.249.22.76:9200/series_index/_refresh
[32mINFO    [0m integration.helpers:helpers.py:367 Calling: GET -- https://10.249.22.76:9200/series_index/_count
[32mINFO    [0m integration.ha.helpers:helpers.py:591 Testing restore for series_index - original count pre-restore: 189, and now, new count: 157
[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Model status:

Model  Controller           Cloud/Region         Version  SLA          Timestamp
test   localhost-localhost  localhost/localhost  3.5.3    unsupported  02:06:58Z

App                       Version  Status  Scale  Charm                     Channel        Rev  Exposed  Message
opensearch                         active      3  opensearch                                 0  no       
s3-integrator                      active      1  s3-integrator             latest/edge     65  no       
self-signed-certificates           active      1  self-signed-certificates  latest/stable  155  no       

Unit                         Workload  Agent  Machine  Public address  Ports     Message
opensearch/0                 active    idle   2        10.249.22.194   9200/tcp  
opensearch/1*                active    idle   3        10.249.22.76    9200/tcp  
opensearch/2                 active    idle   4        10.249.22.156   9200/tcp  
s3-integrator/0*             active    idle   0        10.249.22.20              
self-signed-certificates/0*  active    idle   1        10.249.22.188             

Machine  State    Address        Inst id        Base          AZ  Message
0        started  10.249.22.20   juju-de36dc-0  ubuntu@22.04      Running
1        started  10.249.22.188  juju-de36dc-1  ubuntu@22.04      Running
2        started  10.249.22.194  juju-de36dc-2  ubuntu@22.04      Running
3        started  10.249.22.76   juju-de36dc-3  ubuntu@22.04      Running
4        started  10.249.22.156  juju-de36dc-4  ubuntu@22.04      Running

[32mINFO    [0m pytest_operator.plugin:plugin.py:868 Juju error logs:

machine-0: 01:48:23 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 01:48:23 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-s3-integrator-0: 01:48:23 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-3: 01:48:28 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-3: 01:48:28 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-opensearch-1: 01:48:28 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-1: 01:48:49 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 01:48:49 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-self-signed-certificates-0: 01:48:49 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-4: 01:48:58 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-4: 01:48:58 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-opensearch-2: 01:48:58 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-2: 01:49:10 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 01:49:10 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-opensearch-0: 01:49:10 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-opensearch-1: 01:58:13 ERROR unit.opensearch/1.juju-log certificates:4: err:  / out: keytool error: java.lang.Exception: Keystore file does not exist: /var/snap/opensearch/current/etc/opensearch/certificates/ca.p12

unit-opensearch-1: 01:58:18 ERROR unit.opensearch/1.juju-log upgrade-version-a:2: Cannot connect to the OpenSearch server...
unit-opensearch-1: 01:58:19 ERROR unit.opensearch/1.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-0: 01:58:19 ERROR unit.opensearch/0.juju-log certificates:4: err:  / out: keytool error: java.lang.Exception: Keystore file does not exist: /var/snap/opensearch/current/etc/opensearch/certificates/ca.p12

unit-opensearch-1: 01:58:19 ERROR unit.opensearch/1.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-1: 01:58:19 ERROR unit.opensearch/1.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-1: 01:58:23 ERROR unit.opensearch/1.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-0: 01:58:23 ERROR unit.opensearch/0.juju-log certificates:4: Cannot connect to the OpenSearch server...
unit-opensearch-2: 01:58:24 ERROR unit.opensearch/2.juju-log certificates:4: err:  / out: keytool error: java.lang.Exception: Keystore file does not exist: /var/snap/opensearch/current/etc/opensearch/certificates/ca.p12

unit-opensearch-0: 01:58:25 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-1: 01:58:26 ERROR unit.opensearch/1.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-0: 01:58:26 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-0: 01:58:27 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-0: 01:58:28 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-1: 01:58:29 ERROR unit.opensearch/1.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-2: 01:58:29 ERROR unit.opensearch/2.juju-log node-lock-fallback:1: Cannot connect to the OpenSearch server...
unit-opensearch-0: 01:58:29 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-2: 01:58:30 ERROR unit.opensearch/2.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-0: 01:58:30 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-0: 01:58:31 ERROR unit.opensearch/0.juju-log certificates:4: Cannot connect to the OpenSearch server...
unit-opensearch-2: 01:58:31 ERROR unit.opensearch/2.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-1: 01:58:32 ERROR unit.opensearch/1.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-2: 01:58:32 ERROR unit.opensearch/2.juju-log certificates:4: Cannot connect to the OpenSearch server...
unit-opensearch-0: 01:58:33 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-2: 01:58:33 ERROR unit.opensearch/2.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-0: 01:58:34 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-2: 01:58:34 ERROR unit.opensearch/2.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-0: 01:58:34 ERROR unit.opensearch/0.juju-log node-lock-fallback:1: Cannot connect to the OpenSearch server...
unit-opensearch-2: 01:58:35 ERROR unit.opensearch/2.juju-log node-lock-fallback:1: Cannot connect to the OpenSearch server...
unit-opensearch-0: 01:58:35 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-2: 01:58:36 ERROR unit.opensearch/2.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-0: 01:58:36 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-2: 01:58:37 ERROR unit.opensearch/2.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-0: 01:58:37 ERROR unit.opensearch/0.juju-log opensearch-peers:3: Cannot connect to the OpenSearch server...
unit-opensearch-2: 01:58:38 ERROR unit.opensearch/2.juju-log node-lock-fallback:1: Cannot connect to the OpenSearch server...
unit-opensearch-0: 01:58:38 ERROR unit.opensearch/0.juju-log node-lock-fallback:1: Cannot connect to the OpenSearch server...
unit-opensearch-2: 01:58:39 ERROR unit.opensearch/2.juju-log node-lock-fallback:1: Cannot connect to the OpenSearch server...
unit-opensearch-0: 01:58:39 ERROR unit.opensearch/0.juju-log node-lock-fallback:1: Cannot connect to the OpenSearch server...
unit-opensearch-2: 01:58:40 ERROR unit.opensearch/2.juju-log node-lock-fallback:1: Cannot connect to the OpenSearch server...
unit-opensearch-0: 01:58:40 ERROR unit.opensearch/0.juju-log node-lock-fallback:1: Cannot connect to the OpenSearch server...
unit-opensearch-2: 01:58:41 ERROR unit.opensearch/2.juju-log opensearch-peers:3: Cannot connect to the OpenSearch server...
unit-opensearch-0: 01:58:41 ERROR unit.opensearch/0.juju-log opensearch-peers:3: Cannot connect to the OpenSearch server...
unit-opensearch-2: 01:58:41 ERROR unit.opensearch/2.juju-log opensearch-peers:3: Cannot connect to the OpenSearch server...
unit-opensearch-0: 01:58:42 ERROR unit.opensearch/0.juju-log opensearch-peers:3: Cannot connect to the OpenSearch server...
unit-opensearch-2: 01:58:43 ERROR unit.opensearch/2.juju-log opensearch-peers:3: Cannot connect to the OpenSearch server...
unit-opensearch-0: 01:58:43 ERROR unit.opensearch/0.juju-log opensearch-peers:3: Cannot connect to the OpenSearch server...
unit-opensearch-0: 01:58:44 ERROR unit.opensearch/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-2: 01:58:44 ERROR unit.opensearch/2.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-2: 01:58:50 ERROR unit.opensearch/2.juju-log opensearch-peers:3: Cannot connect to the OpenSearch server...
unit-opensearch-0: 01:58:50 ERROR unit.opensearch/0.juju-log opensearch-peers:3: Cannot connect to the OpenSearch server...
unit-opensearch-0: 01:58:51 ERROR unit.opensearch/0.juju-log opensearch-peers:3: Cannot connect to the OpenSearch server...
unit-opensearch-2: 01:58:51 ERROR unit.opensearch/2.juju-log opensearch-peers:3: Cannot connect to the OpenSearch server...
unit-opensearch-2: 01:58:53 ERROR unit.opensearch/2.juju-log upgrade-version-a:2: Cannot connect to the OpenSearch server...
unit-opensearch-2: 01:58:55 ERROR unit.opensearch/2.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-2: 01:58:59 ERROR unit.opensearch/2.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-2: 01:59:02 ERROR unit.opensearch/2.juju-log node-lock-fallback:1: Cannot connect to the OpenSearch server...
unit-opensearch-2: 01:59:07 ERROR unit.opensearch/2.juju-log node-lock-fallback:1: Cannot connect to the OpenSearch server...
unit-opensearch-2: 01:59:09 ERROR unit.opensearch/2.juju-log node-lock-fallback:1: Cannot connect to the OpenSearch server...
unit-opensearch-1: 02:01:13 ERROR unit.opensearch/1.juju-log s3-credentials:5: Failed to setup backup service with state repository s3 is unreachable
unit-opensearch-1: 02:01:32 ERROR unit.opensearch/1.juju-log s3-credentials:5: Failed to setup backup service with state repository s3 is unreachable

[32mINFO    [0m pytest_operator.plugin:plugin.py:947 Forgetting model main...
[32mINFO    [0m integration.ha.test_backups:test_backups.py:173 Cleaning backups from cloud buckets