[32mINFO    [0m integration.helpers:helpers.py:347 Calling: GET -- https://10.106.99.38:9200/series_index/_search_shards
[32mINFO    [0m integration.helpers:helpers.py:347 Calling: GET -- https://10.106.99.38:9200/
[32mINFO    [0m integration.helpers:helpers.py:347 Calling: GET -- https://10.106.99.38:9200/
[32mINFO    [0m integration.helpers:helpers.py:347 Calling: GET -- https://10.106.99.38:9200/
[32mINFO    [0m integration.helpers:helpers.py:347 Calling: GET -- https://10.106.99.38:9200/
[32mINFO    [0m integration.helpers:helpers.py:347 Calling: GET -- https://10.106.99.21:9200/series_index/_search_shards
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:329 



[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:330 Model  Controller           Cloud/Region         Version  SLA          Timestamp
test   localhost-localhost  localhost/localhost  3.5.3    unsupported  02:00:46Z

App                       Version  Status  Scale  Charm                     Channel        Rev  Exposed  Message
opensearch                         active    2/3  opensearch                                 0  no       
self-signed-certificates           active      1  self-signed-certificates  latest/stable  155  no       

Unit                         Workload  Agent  Machine  Public address  Ports     Message
opensearch/0                 active    idle   1        10.106.99.134   9200/tcp  
opensearch/1*                active    idle   2        10.106.99.21    9200/tcp  
opensearch/2                 unknown   lost   3        10.106.99.38    9200/tcp  agent lost, see 'juju show-status-log opensearch/2'
self-signed-certificates/0*  active    idle   0        10.106.99.179             

Machine  State    Address        Inst id        Base          AZ  Message
0        started  10.106.99.179  juju-76d21a-0  ubuntu@22.04      Running
1        started  10.106.99.134  juju-76d21a-1  ubuntu@22.04      Running
2        started  10.106.99.21   juju-76d21a-2  ubuntu@22.04      Running
3        down     10.106.99.38   juju-76d21a-3  ubuntu@22.04      Running

[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:337 


02:00:46 -- Waiting for model...
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:277 	App: opensearch - Units - conditions unmet.
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:278 
	app: opensearch active -- message: None
		opensearch-0.d1d  -- (10.106.99.134) -- [idle (since: 02:00:40)] active: 
		opensearch-1.d1d* -- (10.106.99.21) -- [idle (since: 01:58:12)] active: 
		opensearch-2.d1d  -- (10.106.99.38) -- [lost (since: 01:55:58)] unknown: agent lost, see 'juju show-status-log opensearch/2'

[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:337 


02:01:03 -- Waiting for model...
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:277 	App: opensearch - Units - conditions unmet.
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:278 
	app: opensearch active -- message: None
		opensearch-0.d1d  -- (10.106.99.134) -- [idle (since: 02:01:00)] active: 
		opensearch-1.d1d* -- (10.106.99.21) -- [executing (since: 02:01:02)] active: 
		opensearch-2.d1d  -- (10.106.99.38) -- [executing (since: 02:00:53)] waiting: Waiting for OpenSearch to start...

[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:337 


02:01:14 -- Waiting for model...
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:277 	App: opensearch - Units - conditions unmet.
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:278 
	app: opensearch active -- message: None
		opensearch-0.d1d  -- (10.106.99.134) -- [idle (since: 02:01:00)] active: 
		opensearch-1.d1d* -- (10.106.99.21) -- [idle (since: 02:01:03)] active: 
		opensearch-2.d1d  -- (10.106.99.38) -- [executing (since: 02:00:53)] waiting: Waiting for OpenSearch to start...

[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:337 


02:01:26 -- Waiting for model...
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:277 	App: opensearch - Units - conditions unmet.
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:278 
	app: opensearch active -- message: None
		opensearch-0.d1d  -- (10.106.99.134) -- [idle (since: 02:01:20)] active: 
		opensearch-1.d1d* -- (10.106.99.21) -- [idle (since: 02:01:22)] active: 
		opensearch-2.d1d  -- (10.106.99.38) -- [idle (since: 02:01:24)] active: 

[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:337 


02:01:38 -- Waiting for model...
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:277 	App: opensearch - Units - conditions unmet.
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:278 
	app: opensearch active -- message: None
		opensearch-0.d1d  -- (10.106.99.134) -- [idle (since: 02:01:20)] active: 
		opensearch-1.d1d* -- (10.106.99.21) -- [idle (since: 02:01:22)] active: 
		opensearch-2.d1d  -- (10.106.99.38) -- [idle (since: 02:01:24)] active: 

[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:337 


02:01:50 -- Waiting for model...
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:277 	App: opensearch - Units - conditions unmet.
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:278 
	app: opensearch active -- message: None
		opensearch-0.d1d  -- (10.106.99.134) -- [idle (since: 02:01:20)] active: 
		opensearch-1.d1d* -- (10.106.99.21) -- [idle (since: 02:01:22)] active: 
		opensearch-2.d1d  -- (10.106.99.38) -- [idle (since: 02:01:24)] active: 

[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:337 


02:02:01 -- Waiting for model...
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:277 	App: opensearch - Units - conditions unmet.
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:278 
	app: opensearch active -- message: None
		opensearch-0.d1d  -- (10.106.99.134) -- [idle (since: 02:01:20)] active: 
		opensearch-1.d1d* -- (10.106.99.21) -- [idle (since: 02:01:22)] active: 
		opensearch-2.d1d  -- (10.106.99.38) -- [idle (since: 02:01:24)] active: 

[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:337 


02:02:13 -- Waiting for model...
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:277 	App: opensearch - Units - conditions unmet.
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:278 
	app: opensearch active -- message: None
		opensearch-0.d1d  -- (10.106.99.134) -- [idle (since: 02:01:20)] active: 
		opensearch-1.d1d* -- (10.106.99.21) -- [idle (since: 02:01:22)] active: 
		opensearch-2.d1d  -- (10.106.99.38) -- [idle (since: 02:01:24)] active: 

[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:337 


02:02:24 -- Waiting for model...
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:277 	App: opensearch - Units - conditions unmet.
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:278 
	app: opensearch active -- message: None
		opensearch-0.d1d  -- (10.106.99.134) -- [idle (since: 02:01:20)] active: 
		opensearch-1.d1d* -- (10.106.99.21) -- [idle (since: 02:01:22)] active: 
		opensearch-2.d1d  -- (10.106.99.38) -- [idle (since: 02:01:24)] active: 

[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:337 


02:02:36 -- Waiting for model...
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:277 	App: opensearch - Units - conditions unmet.
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:278 
	app: opensearch active -- message: None
		opensearch-0.d1d  -- (10.106.99.134) -- [idle (since: 02:01:20)] active: 
		opensearch-1.d1d* -- (10.106.99.21) -- [idle (since: 02:01:22)] active: 
		opensearch-2.d1d  -- (10.106.99.38) -- [idle (since: 02:01:24)] active: 

[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:337 


02:02:48 -- Waiting for model...
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:348 02:02:49 -- Waiting for model: complete.



[1m[31mERROR   [0m integration.ha.helpers:helpers.py:409 Network not restored yet, attempting again.
[1m[31mERROR   [0m integration.ha.helpers:helpers.py:409 Network not restored yet, attempting again.
[1m[31mERROR   [0m integration.ha.helpers:helpers.py:409 Network not restored yet, attempting again.
[1m[31mERROR   [0m integration.ha.helpers:helpers.py:409 Network not restored yet, attempting again.
[1m[31mERROR   [0m integration.ha.helpers:helpers.py:409 Network not restored yet, attempting again.
[1m[31mERROR   [0m integration.ha.helpers:helpers.py:409 Network not restored yet, attempting again.
[1m[31mERROR   [0m integration.ha.helpers:helpers.py:409 Network not restored yet, attempting again.
[1m[31mERROR   [0m integration.ha.helpers:helpers.py:409 Network not restored yet, attempting again.
[1m[31mERROR   [0m integration.ha.helpers:helpers.py:409 Network not restored yet, attempting again.
[1m[31mERROR   [0m integration.ha.helpers:helpers.py:409 Network not restored yet, attempting again.
[1m[31mERROR   [0m integration.ha.helpers:helpers.py:409 Network not restored yet, attempting again.
[1m[31mERROR   [0m integration.ha.helpers:helpers.py:409 Network not restored yet, attempting again.
[1m[31mERROR   [0m integration.ha.helpers:helpers.py:409 Network not restored yet, attempting again.
[1m[31mERROR   [0m integration.ha.helpers:helpers.py:409 Network not restored yet, attempting again.
[1m[31mERROR   [0m integration.ha.helpers:helpers.py:409 Network not restored yet, attempting again.
[32mINFO    [0m integration.helpers:helpers.py:347 Calling: GET -- https://10.106.99.178:9200/
[32mINFO    [0m integration.helpers:helpers.py:347 Calling: GET -- https://10.106.99.21:9200/series_index/_search_shards
[32mINFO    [0m integration.helpers:helpers.py:347 Calling: GET -- https://10.106.99.178:9200/_nodes
[32mINFO    [0m integration.ha.helpers:helpers.py:247 Continuous writes result: namespace(max_stored_id=930, count=931, last_expected_id=930)
[32mINFO    [0m integration.helpers:helpers.py:347 Calling: GET -- https://10.106.99.21:9200/series_index/_search_shards
[32mINFO    [0m integration.ha.conftest:conftest.py:48 



The writes have been cleared.