[32mINFO    [0m integration.ha.test_backups:test_backups.py:490 Remove s3-credentials relation
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  main/0 [idle] active: 
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  main/0 [idle] active: 
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  main/0 [idle] active: 
[32mINFO    [0m integration.ha.test_backups:test_backups.py:502 Re-add s3-credentials relation
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  main/0 [idle] active: 
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  main/0 [executing] maintenance: Configuring backup service...
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  main/0 [idle] active: 
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  main/0 [idle] active: 
[32mINFO    [0m integration.ha.test_backups:test_backups.py:511 Syncing credentials for aws
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  main/0 [idle] active: 
  s3-integrator/0 [idle] active: 
[32mINFO    [0m integration.helpers:helpers.py:347 Calling: GET -- https://10.231.45.212:9200/_recovery?human
[32mINFO    [0m integration.ha.helpers:helpers.py:247 Continuous writes result: namespace(max_stored_id=338, count=339, last_expected_id=338)
[32mINFO    [0m integration.helpers:helpers.py:347 Calling: GET -- https://10.231.45.212:9200/series_index/_search_shards
[32mINFO    [0m integration.helpers:helpers.py:347 Calling: POST -- https://10.231.45.212:9200/series_index/_refresh
[32mINFO    [0m integration.helpers:helpers.py:347 Calling: GET -- https://10.231.45.212:9200/series_index/_count
[32mINFO    [0m integration.helpers:helpers.py:347 Calling: GET -- https://10.231.45.212:9200/_recovery?human
[32mINFO    [0m integration.helpers:helpers.py:347 Calling: POST -- https://10.231.45.212:9200/series_index/_refresh
[32mINFO    [0m integration.helpers:helpers.py:347 Calling: GET -- https://10.231.45.212:9200/series_index/_count
[32mINFO    [0m integration.ha.helpers:helpers.py:591 Testing restore for series_index - original count pre-restore: 339, and now, new count: 309
[32mINFO    [0m integration.helpers:helpers.py:347 Calling: POST -- https://10.231.45.212:9200/series_index/_refresh
[32mINFO    [0m integration.helpers:helpers.py:347 Calling: GET -- https://10.231.45.212:9200/series_index/_count
[32mINFO    [0m integration.ha.conftest:conftest.py:39 



The writes have been cleared.




[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Model status:

Model  Controller           Cloud/Region         Version  SLA          Timestamp
test   localhost-localhost  localhost/localhost  3.5.3    unsupported  02:08:03Z

App                       Version  Status  Scale  Charm                     Channel        Rev  Exposed  Message
failover                           active      2  opensearch                                 1  no       
main                               active      1  opensearch                                 0  no       
opensearch                         active      1  opensearch                                 2  no       
s3-integrator                      active      1  s3-integrator             latest/edge     41  no       
self-signed-certificates           active      1  self-signed-certificates  latest/stable  155  no       

Unit                         Workload  Agent  Machine  Public address  Ports     Message
failover/0*                  active    idle   2        10.231.45.29    9200/tcp  
failover/1                   active    idle   3        10.231.45.160   9200/tcp  
main/0*                      active    idle   5        10.231.45.212   9200/tcp  
opensearch/0*                active    idle   4        10.231.45.91    9200/tcp  
s3-integrator/0*             active    idle   1        10.231.45.154             
self-signed-certificates/0*  active    idle   0        10.231.45.161             

Machine  State    Address        Inst id        Base          AZ  Message
0        started  10.231.45.161  juju-25dde8-0  ubuntu@22.04      Running
1        started  10.231.45.154  juju-25dde8-1  ubuntu@22.04      Running
2        started  10.231.45.29   juju-25dde8-2  ubuntu@22.04      Running
3        started  10.231.45.160  juju-25dde8-3  ubuntu@22.04      Running
4        started  10.231.45.91   juju-25dde8-4  ubuntu@22.04      Running
5        started  10.231.45.212  juju-25dde8-5  ubuntu@22.04      Running

[32mINFO    [0m pytest_operator.plugin:plugin.py:868 Juju error logs:

machine-1: 01:55:22 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 01:55:22 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-s3-integrator-0: 01:55:22 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-0: 01:55:22 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 01:55:22 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-self-signed-certificates-0: 01:55:23 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-2: 01:55:39 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 01:55:39 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-failover-0: 01:55:39 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-5: 01:55:39 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-5: 01:55:39 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-main-0: 01:55:40 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-4: 01:55:40 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-4: 01:55:40 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-opensearch-0: 01:55:40 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-3: 01:55:41 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-3: 01:55:41 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-failover-1: 01:55:41 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-failover-1: 01:57:01 ERROR unit.failover/1.juju-log [Errno 111] Connection refused
unit-failover-1: 01:57:02 ERROR unit.failover/1.juju-log peer-cluster-orchestrator:12: [Errno 111] Connection refused
unit-main-0: 01:57:02 ERROR unit.main/0.juju-log [Errno 111] Connection refused
unit-failover-1: 01:57:03 ERROR unit.failover/1.juju-log peer-cluster-orchestrator:12: [Errno 111] Connection refused
unit-main-0: 01:57:03 ERROR unit.main/0.juju-log peer-cluster-orchestrator:10: [Errno 111] Connection refused
unit-failover-1: 01:57:04 ERROR unit.failover/1.juju-log upgrade-version-a:1: [Errno 111] Connection refused
unit-main-0: 01:57:04 ERROR unit.main/0.juju-log peer-cluster-orchestrator:10: [Errno 111] Connection refused
unit-opensearch-0: 01:57:05 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-failover-1: 01:57:06 ERROR unit.failover/1.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-main-0: 01:57:06 ERROR unit.main/0.juju-log opensearch-peers:9: [Errno 111] Connection refused
unit-main-0: 01:57:06 ERROR unit.main/0.juju-log opensearch-peers:9: [Errno 111] Connection refused
unit-main-0: 01:57:06 ERROR unit.main/0.juju-log opensearch-peers:9: [Errno 111] Connection refused
unit-main-0: 01:57:06 ERROR unit.main/0.juju-log opensearch-peers:9: [Errno 111] Connection refused
unit-opensearch-0: 01:57:06 ERROR unit.opensearch/0.juju-log peer-cluster:12: [Errno 111] Connection refused
unit-failover-1: 01:57:06 ERROR unit.failover/1.juju-log upgrade-version-a:1: [Errno 111] Connection refused
unit-main-0: 01:57:07 ERROR unit.main/0.juju-log upgrade-version-a:8: [Errno 111] Connection refused
unit-opensearch-0: 01:57:07 ERROR unit.opensearch/0.juju-log opensearch-peers:5: [Errno 111] Connection refused
unit-opensearch-0: 01:57:07 ERROR unit.opensearch/0.juju-log opensearch-peers:5: [Errno 111] Connection refused
unit-opensearch-0: 01:57:07 ERROR unit.opensearch/0.juju-log opensearch-peers:5: [Errno 111] Connection refused
unit-opensearch-0: 01:57:07 ERROR unit.opensearch/0.juju-log opensearch-peers:5: [Errno 111] Connection refused
unit-failover-1: 01:57:07 ERROR unit.failover/1.juju-log upgrade-version-a:1: [Errno 111] Connection refused
unit-main-0: 01:57:08 ERROR unit.main/0.juju-log peer-cluster-orchestrator:11: [Errno 111] Connection refused
unit-opensearch-0: 01:57:08 ERROR unit.opensearch/0.juju-log peer-cluster:11: [Errno 111] Connection refused
unit-failover-1: 01:57:08 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-opensearch-0: 01:57:09 ERROR unit.opensearch/0.juju-log peer-cluster:11: [Errno 111] Connection refused
unit-main-0: 01:57:09 ERROR unit.main/0.juju-log peer-cluster-orchestrator:11: [Errno 111] Connection refused
unit-failover-1: 01:57:09 ERROR unit.failover/1.juju-log node-lock-fallback:3: [Errno 111] Connection refused
unit-opensearch-0: 01:57:10 ERROR unit.opensearch/0.juju-log opensearch-peers:5: [Errno 111] Connection refused
unit-opensearch-0: 01:57:10 ERROR unit.opensearch/0.juju-log opensearch-peers:5: [Errno 111] Connection refused
unit-main-0: 01:57:10 ERROR unit.main/0.juju-log certificates:13: [Errno 111] Connection refused
unit-opensearch-0: 01:57:10 ERROR unit.opensearch/0.juju-log opensearch-peers:5: [Errno 111] Connection refused
unit-opensearch-0: 01:57:10 ERROR unit.opensearch/0.juju-log opensearch-peers:5: [Errno 111] Connection refused
unit-failover-1: 01:57:10 ERROR unit.failover/1.juju-log node-lock-fallback:3: [Errno 111] Connection refused
unit-opensearch-0: 01:57:11 ERROR unit.opensearch/0.juju-log peer-cluster:11: [Errno 111] Connection refused
unit-failover-0: 01:57:11 ERROR unit.failover/0.juju-log [Errno 111] Connection refused
unit-failover-1: 01:57:11 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-1: 01:57:11 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-1: 01:57:11 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-1: 01:57:11 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-1: 01:57:11 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-1: 01:57:11 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-1: 01:57:11 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-opensearch-0: 01:57:11 ERROR unit.opensearch/0.juju-log certificates:15: [Errno 111] Connection refused
unit-failover-0: 01:57:12 ERROR unit.failover/0.juju-log peer-cluster-orchestrator:12: [Errno 111] Connection refused
unit-failover-1: 01:57:12 ERROR unit.failover/1.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-failover-0: 01:57:12 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:57:12 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:57:13 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:57:13 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-main-0: 01:57:13 ERROR unit.main/0.juju-log [Errno 111] Connection refused
unit-failover-1: 01:57:13 ERROR unit.failover/1.juju-log upgrade-version-a:1: [Errno 111] Connection refused
unit-failover-0: 01:57:13 ERROR unit.failover/0.juju-log certificates:14: [Errno 111] Connection refused
unit-main-0: 01:57:14 ERROR unit.main/0.juju-log [Errno 111] Connection refused
unit-failover-1: 01:57:14 ERROR unit.failover/1.juju-log certificates:14: [Errno 111] Connection refused
unit-opensearch-0: 01:57:14 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-main-0: 01:57:15 ERROR unit.main/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 01:57:15 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-main-0: 01:57:16 ERROR unit.main/0.juju-log peer-cluster-orchestrator:10: [Errno 111] Connection refused
unit-main-0: 01:57:16 ERROR unit.main/0.juju-log peer-cluster-orchestrator:10: [Errno 111] Connection refused
unit-main-0: 01:57:16 ERROR unit.main/0.juju-log peer-cluster-orchestrator:10: Cannot connect to the OpenSearch server...
unit-main-0: 01:57:16 ERROR unit.main/0.juju-log peer-cluster-orchestrator:10: [Errno 111] Connection refused
unit-opensearch-0: 01:57:16 ERROR unit.opensearch/0.juju-log upgrade-version-a:4: [Errno 111] Connection refused
unit-failover-0: 01:57:16 ERROR unit.failover/0.juju-log [Errno 111] Connection refused
unit-main-0: 01:57:16 ERROR unit.main/0.juju-log peer-cluster-orchestrator:10: [Errno 111] Connection refused
unit-main-0: 01:57:16 ERROR unit.main/0.juju-log peer-cluster-orchestrator:10: Cannot connect to the OpenSearch server...
unit-main-0: 01:57:17 ERROR unit.main/0.juju-log peer-cluster-orchestrator:10: [Errno 111] Connection refused
unit-main-0: 01:57:17 ERROR unit.main/0.juju-log peer-cluster-orchestrator:10: Cannot connect to the OpenSearch server...
unit-failover-1: 01:57:17 ERROR unit.failover/1.juju-log [Errno 111] Connection refused
unit-opensearch-0: 01:57:17 ERROR unit.opensearch/0.juju-log peer-cluster:11: [Errno 111] Connection refused
unit-failover-0: 01:57:17 ERROR unit.failover/0.juju-log [Errno 111] Connection refused
unit-failover-1: 01:57:18 ERROR unit.failover/1.juju-log [Errno 111] Connection refused
unit-opensearch-0: 01:57:18 ERROR unit.opensearch/0.juju-log opensearch-peers:5: [Errno 111] Connection refused
unit-opensearch-0: 01:57:18 ERROR unit.opensearch/0.juju-log opensearch-peers:5: [Errno 111] Connection refused
unit-opensearch-0: 01:57:18 ERROR unit.opensearch/0.juju-log opensearch-peers:5: [Errno 111] Connection refused
unit-opensearch-0: 01:57:18 ERROR unit.opensearch/0.juju-log opensearch-peers:5: [Errno 111] Connection refused
unit-failover-0: 01:57:18 ERROR unit.failover/0.juju-log peer-cluster-orchestrator:12: [Errno 111] Connection refused
unit-failover-1: 01:57:19 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-1: 01:57:19 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-1: 01:57:19 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-opensearch-0: 01:57:19 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-failover-0: 01:57:19 ERROR unit.failover/0.juju-log [Errno 111] Connection refused
unit-failover-1: 01:57:19 ERROR unit.failover/1.juju-log [Errno 111] Connection refused
unit-opensearch-0: 01:57:19 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-failover-0: 01:57:20 ERROR unit.failover/0.juju-log [Errno 111] Connection refused
unit-main-0: 01:57:20 ERROR unit.main/0.juju-log peer-cluster-orchestrator:10: [Errno 111] Connection refused
unit-main-0: 01:57:20 ERROR unit.main/0.juju-log peer-cluster-orchestrator:10: Cannot connect to the OpenSearch server...
unit-failover-1: 01:57:20 ERROR unit.failover/1.juju-log [Errno 111] Connection refused
unit-opensearch-0: 01:57:20 ERROR unit.opensearch/0.juju-log peer-cluster:12: [Errno 111] Connection refused
unit-failover-0: 01:57:20 ERROR unit.failover/0.juju-log upgrade-version-a:1: [Errno 111] Connection refused
unit-failover-1: 01:57:21 ERROR unit.failover/1.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-opensearch-0: 01:57:21 ERROR unit.opensearch/0.juju-log certificates:15: [Errno 111] Connection refused
unit-failover-0: 01:57:21 ERROR unit.failover/0.juju-log node-lock-fallback:3: [Errno 111] Connection refused
unit-failover-1: 01:57:22 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-1: 01:57:22 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-1: 01:57:22 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-1: 01:57:22 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-1: 01:57:22 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-1: 01:57:22 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-opensearch-0: 01:57:22 ERROR unit.opensearch/0.juju-log certificates:15: [Errno 111] Connection refused
unit-failover-1: 01:57:22 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:57:22 ERROR unit.failover/0.juju-log node-lock-fallback:3: [Errno 111] Connection refused
unit-main-0: 01:57:23 ERROR unit.main/0.juju-log peer-cluster-orchestrator:10: [Errno 111] Connection refused
unit-main-0: 01:57:23 ERROR unit.main/0.juju-log peer-cluster-orchestrator:10: Cannot connect to the OpenSearch server...
unit-failover-1: 01:57:23 ERROR unit.failover/1.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-failover-0: 01:57:23 ERROR unit.failover/0.juju-log certificates:14: [Errno 111] Connection refused
unit-opensearch-0: 01:57:23 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-failover-1: 01:57:24 ERROR unit.failover/1.juju-log peer-cluster-orchestrator:12: [Errno 111] Connection refused
unit-failover-0: 01:57:24 ERROR unit.failover/0.juju-log peer-cluster-orchestrator:12: [Errno 111] Connection refused
unit-opensearch-0: 01:57:24 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-failover-1: 01:57:24 ERROR unit.failover/1.juju-log certificates:14: [Errno 111] Connection refused
unit-failover-0: 01:57:25 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-opensearch-0: 01:57:25 ERROR unit.opensearch/0.juju-log peer-cluster:12: [Errno 111] Connection refused
unit-failover-1: 01:57:25 ERROR unit.failover/1.juju-log certificates:14: [Errno 111] Connection refused
unit-failover-0: 01:57:25 ERROR unit.failover/0.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-main-0: 01:57:26 ERROR unit.main/0.juju-log peer-cluster-orchestrator:10: [Errno 111] Connection refused
unit-main-0: 01:57:26 ERROR unit.main/0.juju-log peer-cluster-orchestrator:10: Cannot connect to the OpenSearch server...
unit-opensearch-0: 01:57:26 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-failover-0: 01:57:26 ERROR unit.failover/0.juju-log certificates:14: [Errno 111] Connection refused
unit-failover-1: 01:57:26 ERROR unit.failover/1.juju-log [Errno 111] Connection refused
unit-opensearch-0: 01:57:27 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-failover-1: 01:57:27 ERROR unit.failover/1.juju-log [Errno 111] Connection refused
unit-opensearch-0: 01:57:27 ERROR unit.opensearch/0.juju-log peer-cluster:12: [Errno 111] Connection refused
unit-failover-0: 01:57:28 ERROR unit.failover/0.juju-log [Errno 111] Connection refused
unit-failover-1: 01:57:28 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-1: 01:57:28 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-1: 01:57:28 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-opensearch-0: 01:57:28 ERROR unit.opensearch/0.juju-log peer-cluster:12: [Errno 111] Connection refused
unit-failover-0: 01:57:28 ERROR unit.failover/0.juju-log [Errno 111] Connection refused
unit-main-0: 01:57:29 ERROR unit.main/0.juju-log peer-cluster-orchestrator:10: [Errno 111] Connection refused
unit-main-0: 01:57:29 ERROR unit.main/0.juju-log peer-cluster-orchestrator:10: Cannot connect to the OpenSearch server...
unit-failover-1: 01:57:29 ERROR unit.failover/1.juju-log [Errno 111] Connection refused
unit-opensearch-0: 01:57:29 ERROR unit.opensearch/0.juju-log opensearch-peers:5: [Errno 111] Connection refused
unit-opensearch-0: 01:57:29 ERROR unit.opensearch/0.juju-log opensearch-peers:5: [Errno 111] Connection refused
unit-opensearch-0: 01:57:29 ERROR unit.opensearch/0.juju-log opensearch-peers:5: [Errno 111] Connection refused
unit-opensearch-0: 01:57:29 ERROR unit.opensearch/0.juju-log opensearch-peers:5: [Errno 111] Connection refused
unit-failover-0: 01:57:29 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:57:29 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:57:29 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:57:29 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:57:29 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:57:29 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:57:29 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:57:29 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:57:29 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-1: 01:57:30 ERROR unit.failover/1.juju-log [Errno 111] Connection refused
unit-failover-0: 01:57:30 ERROR unit.failover/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 01:57:30 ERROR unit.opensearch/0.juju-log peer-cluster:12: [Errno 111] Connection refused
unit-failover-0: 01:57:31 ERROR unit.failover/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 01:57:31 ERROR unit.opensearch/0.juju-log opensearch-peers:5: [Errno 111] Connection refused
unit-opensearch-0: 01:57:31 ERROR unit.opensearch/0.juju-log opensearch-peers:5: [Errno 111] Connection refused
unit-opensearch-0: 01:57:31 ERROR unit.opensearch/0.juju-log opensearch-peers:5: [Errno 111] Connection refused
unit-opensearch-0: 01:57:31 ERROR unit.opensearch/0.juju-log opensearch-peers:5: [Errno 111] Connection refused
unit-failover-0: 01:57:32 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:57:32 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:57:32 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:57:32 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:57:32 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:57:33 ERROR unit.failover/0.juju-log upgrade-version-a:1: [Errno 111] Connection refused
unit-opensearch-0: 01:57:33 ERROR unit.opensearch/0.juju-log peer-cluster:12: [Errno 111] Connection refused
unit-failover-0: 01:57:34 ERROR unit.failover/0.juju-log upgrade-version-a:1: [Errno 111] Connection refused
unit-failover-0: 01:57:34 ERROR unit.failover/0.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-failover-0: 01:57:35 ERROR unit.failover/0.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-failover-0: 01:57:39 ERROR unit.failover/0.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-failover-1: 01:57:39 ERROR unit.failover/1.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-opensearch-0: 01:57:39 ERROR unit.opensearch/0.juju-log peer-cluster:11: [Errno 111] Connection refused
unit-failover-0: 01:57:40 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-1: 01:57:40 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:57:40 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-1: 01:57:40 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-opensearch-0: 01:57:40 ERROR unit.opensearch/0.juju-log opensearch-peers:5: [Errno 111] Connection refused
unit-failover-1: 01:57:40 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-opensearch-0: 01:57:40 ERROR unit.opensearch/0.juju-log opensearch-peers:5: [Errno 111] Connection refused
unit-opensearch-0: 01:57:40 ERROR unit.opensearch/0.juju-log opensearch-peers:5: [Errno 111] Connection refused
unit-opensearch-0: 01:57:40 ERROR unit.opensearch/0.juju-log opensearch-peers:5: [Errno 111] Connection refused
unit-failover-0: 01:57:40 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:57:40 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:57:40 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-opensearch-0: 01:57:41 ERROR unit.opensearch/0.juju-log peer-cluster:11: [Errno 111] Connection refused
unit-failover-1: 01:57:41 ERROR unit.failover/1.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-failover-0: 01:57:41 ERROR unit.failover/0.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-failover-1: 01:57:42 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-1: 01:57:42 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:57:42 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-1: 01:57:42 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:57:42 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:57:42 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:57:42 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:57:42 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-opensearch-0: 01:57:43 ERROR unit.opensearch/0.juju-log peer-cluster:12: [Errno 111] Connection refused
unit-opensearch-0: 01:57:44 ERROR unit.opensearch/0.juju-log opensearch-peers:5: [Errno 111] Connection refused
unit-opensearch-0: 01:57:44 ERROR unit.opensearch/0.juju-log opensearch-peers:5: [Errno 111] Connection refused
unit-opensearch-0: 01:57:44 ERROR unit.opensearch/0.juju-log opensearch-peers:5: [Errno 111] Connection refused
unit-opensearch-0: 01:57:44 ERROR unit.opensearch/0.juju-log opensearch-peers:5: [Errno 111] Connection refused
unit-failover-0: 01:57:46 ERROR unit.failover/0.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-opensearch-0: 01:57:46 ERROR unit.opensearch/0.juju-log peer-cluster:11: [Errno 111] Connection refused
unit-failover-1: 01:57:46 ERROR unit.failover/1.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-failover-1: 01:57:46 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-1: 01:57:46 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-opensearch-0: 01:57:46 ERROR unit.opensearch/0.juju-log opensearch-peers:5: [Errno 111] Connection refused
unit-failover-0: 01:57:46 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-opensearch-0: 01:57:46 ERROR unit.opensearch/0.juju-log opensearch-peers:5: [Errno 111] Connection refused
unit-opensearch-0: 01:57:46 ERROR unit.opensearch/0.juju-log opensearch-peers:5: [Errno 111] Connection refused
unit-failover-1: 01:57:47 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:57:47 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-opensearch-0: 01:57:47 ERROR unit.opensearch/0.juju-log opensearch-peers:5: [Errno 111] Connection refused
unit-failover-0: 01:57:47 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:57:47 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:57:47 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:57:50 ERROR unit.failover/0.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-failover-1: 01:57:50 ERROR unit.failover/1.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-opensearch-0: 01:57:50 ERROR unit.opensearch/0.juju-log peer-cluster:11: [Errno 111] Connection refused
unit-failover-0: 01:57:50 ERROR unit.failover/0.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-failover-0: 01:57:50 ERROR unit.failover/0.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-opensearch-0: 01:57:51 ERROR unit.opensearch/0.juju-log opensearch-peers:5: [Errno 111] Connection refused
unit-opensearch-0: 01:57:51 ERROR unit.opensearch/0.juju-log opensearch-peers:5: [Errno 111] Connection refused
unit-opensearch-0: 01:57:51 ERROR unit.opensearch/0.juju-log opensearch-peers:5: [Errno 111] Connection refused
unit-opensearch-0: 01:57:51 ERROR unit.opensearch/0.juju-log opensearch-peers:5: [Errno 111] Connection refused
unit-failover-0: 01:57:51 ERROR unit.failover/0.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-failover-0: 01:57:51 ERROR unit.failover/0.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-failover-0: 01:57:51 ERROR unit.failover/0.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-failover-0: 01:57:51 ERROR unit.failover/0.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-failover-1: 01:57:52 ERROR unit.failover/1.juju-log [Errno 111] Connection refused
unit-failover-0: 01:57:52 ERROR unit.failover/0.juju-log [Errno 111] Connection refused
unit-failover-1: 01:57:52 ERROR unit.failover/1.juju-log [Errno 111] Connection refused
unit-failover-0: 01:57:52 ERROR unit.failover/0.juju-log [Errno 111] Connection refused
unit-failover-1: 01:57:53 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:57:53 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-1: 01:57:53 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:57:53 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:57:54 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:57:54 ERROR unit.failover/0.juju-log opensearch-peers:2: Cannot connect to the OpenSearch server...
unit-failover-0: 01:57:54 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-1: 01:57:54 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-1: 01:57:54 ERROR unit.failover/1.juju-log opensearch-peers:2: Cannot connect to the OpenSearch server...
unit-failover-0: 01:57:54 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-1: 01:57:54 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-1: 01:57:54 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:57:54 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:57:54 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-1: 01:57:54 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:57:54 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-1: 01:57:54 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:57:54 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-1: 01:57:54 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:57:54 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-1: 01:57:54 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-1: 01:57:54 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:57:54 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:57:55 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-1: 01:57:55 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-1: 01:57:55 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-1: 01:57:55 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-1: 01:57:55 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:57:55 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:57:55 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:57:55 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:57:55 ERROR unit.failover/0.juju-log opensearch-peers:2: Cannot connect to the OpenSearch server...
unit-failover-0: 01:57:55 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:57:58 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-opensearch-0: 01:57:59 ERROR unit.opensearch/0.juju-log peer-cluster:11: [Errno 111] Connection refused
unit-failover-1: 01:57:59 ERROR unit.failover/1.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-failover-1: 01:57:59 ERROR unit.failover/1.juju-log peer-cluster:10: Cannot connect to the OpenSearch server...
unit-failover-1: 01:57:59 ERROR unit.failover/1.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-failover-1: 01:57:59 ERROR unit.failover/1.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-failover-1: 01:57:59 ERROR unit.failover/1.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-failover-1: 01:57:59 ERROR unit.failover/1.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-opensearch-0: 01:58:00 ERROR unit.opensearch/0.juju-log peer-cluster:11: [Errno 111] Connection refused
unit-failover-1: 01:58:00 ERROR unit.failover/1.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-failover-1: 01:58:00 ERROR unit.failover/1.juju-log peer-cluster:10: Cannot connect to the OpenSearch server...
unit-failover-1: 01:58:00 ERROR unit.failover/1.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-failover-1: 01:58:00 ERROR unit.failover/1.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-failover-1: 01:58:01 ERROR unit.failover/1.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-failover-1: 01:58:01 ERROR unit.failover/1.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-failover-0: 01:58:01 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:58:04 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:58:07 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:58:11 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:58:11 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-opensearch-0: 01:58:12 ERROR unit.opensearch/0.juju-log peer-cluster:12: [Errno 111] Connection refused
unit-failover-1: 01:58:12 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-1: 01:58:12 ERROR unit.failover/1.juju-log opensearch-peers:2: Cannot connect to the OpenSearch server...
unit-failover-1: 01:58:12 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:58:12 ERROR unit.failover/0.juju-log [Errno 111] Connection refused
unit-failover-0: 01:58:13 ERROR unit.failover/0.juju-log [Errno 111] Connection refused
unit-failover-1: 01:58:13 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:58:13 ERROR unit.failover/0.juju-log [Errno 111] Connection refused
unit-failover-1: 01:58:13 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:58:13 ERROR unit.failover/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 01:58:13 ERROR unit.opensearch/0.juju-log opensearch-peers:5: [Errno 111] Connection refused
unit-opensearch-0: 01:58:13 ERROR unit.opensearch/0.juju-log opensearch-peers:5: [Errno 111] Connection refused
unit-opensearch-0: 01:58:13 ERROR unit.opensearch/0.juju-log opensearch-peers:5: [Errno 111] Connection refused
unit-opensearch-0: 01:58:13 ERROR unit.opensearch/0.juju-log opensearch-peers:5: [Errno 111] Connection refused
unit-failover-0: 01:58:13 ERROR unit.failover/0.juju-log [Errno 111] Connection refused
unit-failover-1: 01:58:14 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-1: 01:58:14 ERROR unit.failover/1.juju-log opensearch-peers:2: Cannot connect to the OpenSearch server...
unit-failover-1: 01:58:14 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-1: 01:58:15 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-1: 01:58:15 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-1: 01:58:15 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-1: 01:58:15 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-1: 01:58:15 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:58:15 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:58:15 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-1: 01:58:15 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-1: 01:58:16 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-1: 01:58:16 ERROR unit.failover/1.juju-log opensearch-peers:2: Cannot connect to the OpenSearch server...
unit-failover-1: 01:58:16 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:58:17 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:58:17 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:58:17 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:58:17 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:58:17 ERROR unit.failover/0.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-opensearch-0: 01:58:18 ERROR unit.opensearch/0.juju-log peer-cluster:12: [Errno 111] Connection refused
unit-failover-0: 01:58:19 ERROR unit.failover/0.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-opensearch-0: 01:58:19 ERROR unit.opensearch/0.juju-log opensearch-peers:5: [Errno 111] Connection refused
unit-failover-1: 01:58:19 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-0: 01:58:19 ERROR unit.failover/0.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-opensearch-0: 01:58:19 ERROR unit.opensearch/0.juju-log opensearch-peers:5: [Errno 111] Connection refused
unit-opensearch-0: 01:58:20 ERROR unit.opensearch/0.juju-log opensearch-peers:5: [Errno 111] Connection refused
unit-opensearch-0: 01:58:20 ERROR unit.opensearch/0.juju-log opensearch-peers:5: [Errno 111] Connection refused
unit-failover-0: 01:58:20 ERROR unit.failover/0.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-failover-1: 01:58:22 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-1: 01:58:25 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-failover-1: 01:58:28 ERROR unit.failover/1.juju-log opensearch-peers:2: [Errno 111] Connection refused
unit-opensearch-0: 01:58:36 ERROR unit.opensearch/0.juju-log peer-cluster:12: [Errno 111] Connection refused
unit-opensearch-0: 01:58:37 ERROR unit.opensearch/0.juju-log peer-cluster:12: [Errno 111] Connection refused
unit-opensearch-0: 01:58:37 ERROR unit.opensearch/0.juju-log peer-cluster:12: [Errno 111] Connection refused
unit-opensearch-0: 01:58:38 ERROR unit.opensearch/0.juju-log peer-cluster:12: [Errno 111] Connection refused
unit-opensearch-0: 01:58:39 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 01:58:40 ERROR unit.opensearch/0.juju-log opensearch-peers:5: [Errno 111] Connection refused
unit-opensearch-0: 01:58:41 ERROR unit.opensearch/0.juju-log opensearch-peers:5: [Errno 111] Connection refused
unit-opensearch-0: 01:58:41 ERROR unit.opensearch/0.juju-log opensearch-peers:5: Cannot connect to the OpenSearch server...
unit-opensearch-0: 01:58:41 ERROR unit.opensearch/0.juju-log opensearch-peers:5: [Errno 111] Connection refused
unit-opensearch-0: 01:58:41 ERROR unit.opensearch/0.juju-log opensearch-peers:5: [Errno 111] Connection refused
unit-opensearch-0: 01:58:41 ERROR unit.opensearch/0.juju-log opensearch-peers:5: [Errno 111] Connection refused
unit-opensearch-0: 01:58:41 ERROR unit.opensearch/0.juju-log opensearch-peers:5: [Errno 111] Connection refused
unit-opensearch-0: 01:58:42 ERROR unit.opensearch/0.juju-log opensearch-peers:5: [Errno 111] Connection refused
unit-opensearch-0: 01:58:42 ERROR unit.opensearch/0.juju-log opensearch-peers:5: [Errno 111] Connection refused
unit-opensearch-0: 01:58:43 ERROR unit.opensearch/0.juju-log opensearch-peers:5: [Errno 111] Connection refused
unit-opensearch-0: 01:58:43 ERROR unit.opensearch/0.juju-log opensearch-peers:5: Cannot connect to the OpenSearch server...
unit-opensearch-0: 01:58:43 ERROR unit.opensearch/0.juju-log opensearch-peers:5: [Errno 111] Connection refused
unit-opensearch-0: 01:58:46 ERROR unit.opensearch/0.juju-log opensearch-peers:5: [Errno 111] Connection refused
unit-opensearch-0: 01:58:49 ERROR unit.opensearch/0.juju-log opensearch-peers:5: [Errno 111] Connection refused
unit-opensearch-0: 01:58:52 ERROR unit.opensearch/0.juju-log opensearch-peers:5: [Errno 111] Connection refused
unit-opensearch-0: 01:58:55 ERROR unit.opensearch/0.juju-log opensearch-peers:5: [Errno 111] Connection refused
unit-main-0: 02:00:35 ERROR unit.main/0.juju-log s3-credentials:16: Plugin repository-s3 missing: ['access-key', 'secret-key']
unit-main-0: 02:00:37 ERROR unit.main/0.juju-log s3-credentials:16: Plugin repository-s3 missing: ['access-key', 'secret-key']
unit-main-0: 02:00:39 ERROR unit.main/0.juju-log s3-credentials:16: Plugin repository-s3 missing: ['access-key', 'secret-key']
unit-main-0: 02:00:48 ERROR unit.main/0.juju-log s3-credentials:16: Request PUT to https://10.231.45.212:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'http://localhost', 'protocol': 'http', 'bucket': 'error', 'base_path': '/', 'region': 'default'}} failed.(Attempts left: 5)
	Error: 500 Server Error: Internal Server Error for url: https://10.231.45.212:9200/_snapshot/s3-repository
unit-main-0: 02:00:49 ERROR unit.main/0.juju-log s3-credentials:16: Request PUT to https://10.231.45.212:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'http://localhost', 'protocol': 'http', 'bucket': 'error', 'base_path': '/', 'region': 'default'}} failed.(Attempts left: 4)
	Error: 500 Server Error: Internal Server Error for url: https://10.231.45.212:9200/_snapshot/s3-repository
unit-main-0: 02:00:51 ERROR unit.main/0.juju-log s3-credentials:16: Request PUT to https://10.231.45.212:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'http://localhost', 'protocol': 'http', 'bucket': 'error', 'base_path': '/', 'region': 'default'}} failed.(Attempts left: 3)
	Error: 500 Server Error: Internal Server Error for url: https://10.231.45.212:9200/_snapshot/s3-repository
unit-main-0: 02:00:52 ERROR unit.main/0.juju-log s3-credentials:16: Request PUT to https://10.231.45.212:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'http://localhost', 'protocol': 'http', 'bucket': 'error', 'base_path': '/', 'region': 'default'}} failed.(Attempts left: 2)
	Error: 500 Server Error: Internal Server Error for url: https://10.231.45.212:9200/_snapshot/s3-repository
unit-main-0: 02:00:53 ERROR unit.main/0.juju-log s3-credentials:16: Request PUT to https://10.231.45.212:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'http://localhost', 'protocol': 'http', 'bucket': 'error', 'base_path': '/', 'region': 'default'}} failed.(Attempts left: 1)
	Error: 500 Server Error: Internal Server Error for url: https://10.231.45.212:9200/_snapshot/s3-repository
unit-main-0: 02:00:55 ERROR unit.main/0.juju-log s3-credentials:16: Failed to setup backup service with state repository s3 is unreachable
unit-main-0: 02:01:04 ERROR unit.main/0.juju-log s3-credentials:16: Request PUT to https://10.231.45.212:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'http://localhost', 'protocol': 'http', 'bucket': 'error', 'base_path': '/', 'region': 'default'}} failed.(Attempts left: 5)
	Error: 500 Server Error: Internal Server Error for url: https://10.231.45.212:9200/_snapshot/s3-repository
unit-main-0: 02:01:06 ERROR unit.main/0.juju-log s3-credentials:16: Request PUT to https://10.231.45.212:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'http://localhost', 'protocol': 'http', 'bucket': 'error', 'base_path': '/', 'region': 'default'}} failed.(Attempts left: 4)
	Error: 500 Server Error: Internal Server Error for url: https://10.231.45.212:9200/_snapshot/s3-repository
unit-main-0: 02:01:07 ERROR unit.main/0.juju-log s3-credentials:16: Request PUT to https://10.231.45.212:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'http://localhost', 'protocol': 'http', 'bucket': 'error', 'base_path': '/', 'region': 'default'}} failed.(Attempts left: 3)
	Error: 500 Server Error: Internal Server Error for url: https://10.231.45.212:9200/_snapshot/s3-repository
unit-main-0: 02:01:08 ERROR unit.main/0.juju-log s3-credentials:16: Request PUT to https://10.231.45.212:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'http://localhost', 'protocol': 'http', 'bucket': 'error', 'base_path': '/', 'region': 'default'}} failed.(Attempts left: 2)
	Error: 500 Server Error: Internal Server Error for url: https://10.231.45.212:9200/_snapshot/s3-repository
unit-main-0: 02:01:10 ERROR unit.main/0.juju-log s3-credentials:16: Request PUT to https://10.231.45.212:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'http://localhost', 'protocol': 'http', 'bucket': 'error', 'base_path': '/', 'region': 'default'}} failed.(Attempts left: 1)
	Error: 500 Server Error: Internal Server Error for url: https://10.231.45.212:9200/_snapshot/s3-repository
unit-main-0: 02:01:11 ERROR unit.main/0.juju-log s3-credentials:16: Failed to setup backup service with state repository s3 is unreachable
unit-main-0: 02:01:22 ERROR unit.main/0.juju-log s3-credentials:16: Request PUT to https://10.231.45.212:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'http://localhost', 'protocol': 'http', 'bucket': 'error', 'base_path': '/', 'region': 'default'}} failed.(Attempts left: 5)
	Error: 500 Server Error: Internal Server Error for url: https://10.231.45.212:9200/_snapshot/s3-repository
unit-main-0: 02:01:24 ERROR unit.main/0.juju-log s3-credentials:16: Request PUT to https://10.231.45.212:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'http://localhost', 'protocol': 'http', 'bucket': 'error', 'base_path': '/', 'region': 'default'}} failed.(Attempts left: 4)
	Error: 500 Server Error: Internal Server Error for url: https://10.231.45.212:9200/_snapshot/s3-repository
unit-main-0: 02:01:25 ERROR unit.main/0.juju-log s3-credentials:16: Request PUT to https://10.231.45.212:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'http://localhost', 'protocol': 'http', 'bucket': 'error', 'base_path': '/', 'region': 'default'}} failed.(Attempts left: 3)
	Error: 500 Server Error: Internal Server Error for url: https://10.231.45.212:9200/_snapshot/s3-repository
unit-main-0: 02:01:26 ERROR unit.main/0.juju-log s3-credentials:16: Request PUT to https://10.231.45.212:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'http://localhost', 'protocol': 'http', 'bucket': 'error', 'base_path': '/', 'region': 'default'}} failed.(Attempts left: 2)
	Error: 500 Server Error: Internal Server Error for url: https://10.231.45.212:9200/_snapshot/s3-repository
unit-main-0: 02:01:28 ERROR unit.main/0.juju-log s3-credentials:16: Request PUT to https://10.231.45.212:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'http://localhost', 'protocol': 'http', 'bucket': 'error', 'base_path': '/', 'region': 'default'}} failed.(Attempts left: 1)
	Error: 500 Server Error: Internal Server Error for url: https://10.231.45.212:9200/_snapshot/s3-repository
unit-main-0: 02:01:29 ERROR unit.main/0.juju-log s3-credentials:16: Failed to setup backup service with state repository s3 is unreachable
unit-main-0: 02:01:40 ERROR unit.main/0.juju-log s3-credentials:16: Request PUT to https://10.231.45.212:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'https://s3.amazonaws.com', 'protocol': 'https', 'bucket': 'data-charms-testing', 'base_path': 'opensearch/de1c67b5-83c5-44f4-9323-31264cf97f3c', 'region': 'us-east-1'}} failed.(Attempts left: 5)
	Error: 500 Server Error: Internal Server Error for url: https://10.231.45.212:9200/_snapshot/s3-repository
unit-main-0: 02:01:42 ERROR unit.main/0.juju-log s3-credentials:16: Request PUT to https://10.231.45.212:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'https://s3.amazonaws.com', 'protocol': 'https', 'bucket': 'data-charms-testing', 'base_path': 'opensearch/de1c67b5-83c5-44f4-9323-31264cf97f3c', 'region': 'us-east-1'}} failed.(Attempts left: 4)
	Error: 500 Server Error: Internal Server Error for url: https://10.231.45.212:9200/_snapshot/s3-repository
unit-main-0: 02:01:43 ERROR unit.main/0.juju-log s3-credentials:16: Request PUT to https://10.231.45.212:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'https://s3.amazonaws.com', 'protocol': 'https', 'bucket': 'data-charms-testing', 'base_path': 'opensearch/de1c67b5-83c5-44f4-9323-31264cf97f3c', 'region': 'us-east-1'}} failed.(Attempts left: 3)
	Error: 500 Server Error: Internal Server Error for url: https://10.231.45.212:9200/_snapshot/s3-repository
unit-main-0: 02:01:44 ERROR unit.main/0.juju-log s3-credentials:16: Request PUT to https://10.231.45.212:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'https://s3.amazonaws.com', 'protocol': 'https', 'bucket': 'data-charms-testing', 'base_path': 'opensearch/de1c67b5-83c5-44f4-9323-31264cf97f3c', 'region': 'us-east-1'}} failed.(Attempts left: 2)
	Error: 500 Server Error: Internal Server Error for url: https://10.231.45.212:9200/_snapshot/s3-repository
unit-main-0: 02:01:46 ERROR unit.main/0.juju-log s3-credentials:16: Request PUT to https://10.231.45.212:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'https://s3.amazonaws.com', 'protocol': 'https', 'bucket': 'data-charms-testing', 'base_path': 'opensearch/de1c67b5-83c5-44f4-9323-31264cf97f3c', 'region': 'us-east-1'}} failed.(Attempts left: 1)
	Error: 500 Server Error: Internal Server Error for url: https://10.231.45.212:9200/_snapshot/s3-repository
unit-failover-0: 02:01:52 ERROR unit.failover/0.juju-log /snap/opensearch/current/usr/share/opensearch/bin/opensearch-keystore remove s3.client.default.access_key:
 Stderr: warning: no-jdk distributions that do not bundle a JDK are deprecated and will be removed in a future release
ERROR: Setting [s3.client.default.access_key] does not exist in the keystore.

 Stdout: 
unit-opensearch-0: 02:01:52 ERROR unit.opensearch/0.juju-log /snap/opensearch/current/usr/share/opensearch/bin/opensearch-keystore remove s3.client.default.access_key:
 Stderr: warning: no-jdk distributions that do not bundle a JDK are deprecated and will be removed in a future release
ERROR: Setting [s3.client.default.access_key] does not exist in the keystore.

 Stdout: 
unit-failover-0: 02:01:54 ERROR unit.failover/0.juju-log /snap/opensearch/current/usr/share/opensearch/bin/opensearch-keystore remove s3.client.default.access_key:
 Stderr: warning: no-jdk distributions that do not bundle a JDK are deprecated and will be removed in a future release
ERROR: Setting [s3.client.default.access_key] does not exist in the keystore.

 Stdout: 
unit-opensearch-0: 02:01:54 ERROR unit.opensearch/0.juju-log /snap/opensearch/current/usr/share/opensearch/bin/opensearch-keystore remove s3.client.default.access_key:
 Stderr: warning: no-jdk distributions that do not bundle a JDK are deprecated and will be removed in a future release
ERROR: Setting [s3.client.default.access_key] does not exist in the keystore.

 Stdout: 
unit-failover-0: 02:01:55 ERROR unit.failover/0.juju-log /snap/opensearch/current/usr/share/opensearch/bin/opensearch-keystore remove s3.client.default.access_key:
 Stderr: warning: no-jdk distributions that do not bundle a JDK are deprecated and will be removed in a future release
ERROR: Setting [s3.client.default.access_key] does not exist in the keystore.

 Stdout: 
unit-opensearch-0: 02:01:56 ERROR unit.opensearch/0.juju-log /snap/opensearch/current/usr/share/opensearch/bin/opensearch-keystore remove s3.client.default.access_key:
 Stderr: warning: no-jdk distributions that do not bundle a JDK are deprecated and will be removed in a future release
ERROR: Setting [s3.client.default.access_key] does not exist in the keystore.

 Stdout: 
unit-failover-0: 02:01:56 ERROR unit.failover/0.juju-log /snap/opensearch/current/usr/share/opensearch/bin/opensearch-keystore remove s3.client.default.secret_key:
 Stderr: warning: no-jdk distributions that do not bundle a JDK are deprecated and will be removed in a future release
ERROR: Setting [s3.client.default.secret_key] does not exist in the keystore.

 Stdout: 
unit-opensearch-0: 02:01:57 ERROR unit.opensearch/0.juju-log /snap/opensearch/current/usr/share/opensearch/bin/opensearch-keystore remove s3.client.default.secret_key:
 Stderr: warning: no-jdk distributions that do not bundle a JDK are deprecated and will be removed in a future release
ERROR: Setting [s3.client.default.secret_key] does not exist in the keystore.

 Stdout: 
unit-failover-0: 02:01:58 ERROR unit.failover/0.juju-log /snap/opensearch/current/usr/share/opensearch/bin/opensearch-keystore remove s3.client.default.secret_key:
 Stderr: warning: no-jdk distributions that do not bundle a JDK are deprecated and will be removed in a future release
ERROR: Setting [s3.client.default.secret_key] does not exist in the keystore.

 Stdout: 
unit-opensearch-0: 02:01:58 ERROR unit.opensearch/0.juju-log /snap/opensearch/current/usr/share/opensearch/bin/opensearch-keystore remove s3.client.default.secret_key:
 Stderr: warning: no-jdk distributions that do not bundle a JDK are deprecated and will be removed in a future release
ERROR: Setting [s3.client.default.secret_key] does not exist in the keystore.

 Stdout: 
unit-failover-0: 02:02:00 ERROR unit.failover/0.juju-log /snap/opensearch/current/usr/share/opensearch/bin/opensearch-keystore remove s3.client.default.secret_key:
 Stderr: warning: no-jdk distributions that do not bundle a JDK are deprecated and will be removed in a future release
ERROR: Setting [s3.client.default.secret_key] does not exist in the keystore.

 Stdout: 
unit-opensearch-0: 02:02:00 ERROR unit.opensearch/0.juju-log /snap/opensearch/current/usr/share/opensearch/bin/opensearch-keystore remove s3.client.default.secret_key:
 Stderr: warning: no-jdk distributions that do not bundle a JDK are deprecated and will be removed in a future release
ERROR: Setting [s3.client.default.secret_key] does not exist in the keystore.

 Stdout: 
unit-main-0: 02:04:53 ERROR unit.main/0.juju-log s3-credentials:19: Request PUT to https://10.231.45.212:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'https://s3.amazonaws.com', 'protocol': 'https', 'bucket': 'data-charms-testing', 'base_path': 'opensearch/de1c67b5-83c5-44f4-9323-31264cf97f3c', 'region': 'us-east-1'}} failed.(Attempts left: 5)
	Error: 500 Server Error: Internal Server Error for url: https://10.231.45.212:9200/_snapshot/s3-repository
unit-main-0: 02:04:55 ERROR unit.main/0.juju-log s3-credentials:19: Request PUT to https://10.231.45.212:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'https://s3.amazonaws.com', 'protocol': 'https', 'bucket': 'data-charms-testing', 'base_path': 'opensearch/de1c67b5-83c5-44f4-9323-31264cf97f3c', 'region': 'us-east-1'}} failed.(Attempts left: 4)
	Error: 500 Server Error: Internal Server Error for url: https://10.231.45.212:9200/_snapshot/s3-repository
unit-main-0: 02:04:56 ERROR unit.main/0.juju-log s3-credentials:19: Request PUT to https://10.231.45.212:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'https://s3.amazonaws.com', 'protocol': 'https', 'bucket': 'data-charms-testing', 'base_path': 'opensearch/de1c67b5-83c5-44f4-9323-31264cf97f3c', 'region': 'us-east-1'}} failed.(Attempts left: 3)
	Error: 500 Server Error: Internal Server Error for url: https://10.231.45.212:9200/_snapshot/s3-repository
unit-main-0: 02:04:58 ERROR unit.main/0.juju-log s3-credentials:19: Request PUT to https://10.231.45.212:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'https://s3.amazonaws.com', 'protocol': 'https', 'bucket': 'data-charms-testing', 'base_path': 'opensearch/de1c67b5-83c5-44f4-9323-31264cf97f3c', 'region': 'us-east-1'}} failed.(Attempts left: 2)
	Error: 500 Server Error: Internal Server Error for url: https://10.231.45.212:9200/_snapshot/s3-repository
unit-main-0: 02:04:59 ERROR unit.main/0.juju-log s3-credentials:19: Request PUT to https://10.231.45.212:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'https://s3.amazonaws.com', 'protocol': 'https', 'bucket': 'data-charms-testing', 'base_path': 'opensearch/de1c67b5-83c5-44f4-9323-31264cf97f3c', 'region': 'us-east-1'}} failed.(Attempts left: 1)
	Error: 500 Server Error: Internal Server Error for url: https://10.231.45.212:9200/_snapshot/s3-repository
unit-main-0: 02:05:11 ERROR unit.main/0.juju-log s3-credentials:19: Request PUT to https://10.231.45.212:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'https://s3.amazonaws.com', 'protocol': 'https', 'bucket': 'data-charms-testing', 'base_path': 'opensearch/de1c67b5-83c5-44f4-9323-31264cf97f3c', 'region': 'us-east-1'}} failed.(Attempts left: 5)
	Error: 500 Server Error: Internal Server Error for url: https://10.231.45.212:9200/_snapshot/s3-repository
unit-main-0: 02:05:12 ERROR unit.main/0.juju-log s3-credentials:19: Request PUT to https://10.231.45.212:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'https://s3.amazonaws.com', 'protocol': 'https', 'bucket': 'data-charms-testing', 'base_path': 'opensearch/de1c67b5-83c5-44f4-9323-31264cf97f3c', 'region': 'us-east-1'}} failed.(Attempts left: 4)
	Error: 500 Server Error: Internal Server Error for url: https://10.231.45.212:9200/_snapshot/s3-repository
unit-main-0: 02:05:14 ERROR unit.main/0.juju-log s3-credentials:19: Request PUT to https://10.231.45.212:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'https://s3.amazonaws.com', 'protocol': 'https', 'bucket': 'data-charms-testing', 'base_path': 'opensearch/de1c67b5-83c5-44f4-9323-31264cf97f3c', 'region': 'us-east-1'}} failed.(Attempts left: 3)
	Error: 500 Server Error: Internal Server Error for url: https://10.231.45.212:9200/_snapshot/s3-repository
unit-main-0: 02:05:15 ERROR unit.main/0.juju-log s3-credentials:19: Request PUT to https://10.231.45.212:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'https://s3.amazonaws.com', 'protocol': 'https', 'bucket': 'data-charms-testing', 'base_path': 'opensearch/de1c67b5-83c5-44f4-9323-31264cf97f3c', 'region': 'us-east-1'}} failed.(Attempts left: 2)
	Error: 500 Server Error: Internal Server Error for url: https://10.231.45.212:9200/_snapshot/s3-repository
unit-main-0: 02:05:16 ERROR unit.main/0.juju-log s3-credentials:19: Request PUT to https://10.231.45.212:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'https://s3.amazonaws.com', 'protocol': 'https', 'bucket': 'data-charms-testing', 'base_path': 'opensearch/de1c67b5-83c5-44f4-9323-31264cf97f3c', 'region': 'us-east-1'}} failed.(Attempts left: 1)
	Error: 500 Server Error: Internal Server Error for url: https://10.231.45.212:9200/_snapshot/s3-repository

[32mINFO    [0m pytest_operator.plugin:plugin.py:947 Forgetting model main...
[32mINFO    [0m integration.ha.test_backups:test_backups.py:173 Cleaning backups from cloud buckets