[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:329 



[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:330 Model  Controller           Cloud/Region         Version  SLA          Timestamp
test   localhost-localhost  localhost/localhost  3.5.3    unsupported  02:09:33Z

App                       Version  Status   Scale  Charm                     Channel        Rev  Exposed  Message
opensearch-data                    active       2  opensearch                                 0  no       
opensearch-failover                blocked      1  opensearch                                 2  no       Cannot start. Waiting for peer cluster relation...
opensearch-main                    active       1  opensearch                                 1  no       
self-signed-certificates           active       1  self-signed-certificates  latest/stable  155  no       

Unit                         Workload  Agent      Machine  Public address  Ports     Message
opensearch-data/0            active    executing  3        10.161.222.64   9200/tcp  
opensearch-data/1*           active    executing  4        10.161.222.150  9200/tcp  
opensearch-failover/0*       active    executing  2        10.161.222.138            
opensearch-main/0*           active    executing  1        10.161.222.32   9200/tcp  
self-signed-certificates/0*  active    idle       0        10.161.222.106            

Machine  State    Address         Inst id        Base          AZ  Message
0        started  10.161.222.106  juju-69157d-0  ubuntu@22.04      Running
1        started  10.161.222.32   juju-69157d-1  ubuntu@22.04      Running
2        started  10.161.222.138  juju-69157d-2  ubuntu@22.04      Running
3        started  10.161.222.64   juju-69157d-3  ubuntu@22.04      Running
4        started  10.161.222.150  juju-69157d-4  ubuntu@22.04      Running

[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:337 


02:09:33 -- Waiting for model...
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:277 	App: opensearch-main - Units - conditions unmet.
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:278 
	app: opensearch active -- message: None
		opensearch-main-0.13e* -- (10.161.222.32) -- [executing (since: 02:09:33)] active: 

[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:337 


02:09:43 -- Waiting for model...
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:277 	App: opensearch-main - Units - conditions unmet.
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:278 
	app: opensearch active -- message: None
		opensearch-main-0.13e* -- (10.161.222.32) -- [idle (since: 02:09:42)] active: 

[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:337 


02:09:54 -- Waiting for model...
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:277 	App: opensearch-main - Units - conditions unmet.
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:278 
	app: opensearch active -- message: None
		opensearch-main-0.13e* -- (10.161.222.32) -- [idle (since: 02:09:42)] active: 

[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:337 


02:10:05 -- Waiting for model...
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:277 	App: opensearch-main - Units - conditions unmet.
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:278 
	app: opensearch active -- message: None
		opensearch-main-0.13e* -- (10.161.222.32) -- [idle (since: 02:09:42)] active: 

[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:337 


02:10:16 -- Waiting for model...
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:277 	App: opensearch-main - Units - conditions unmet.
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:278 
	app: opensearch active -- message: None
		opensearch-main-0.13e* -- (10.161.222.32) -- [idle (since: 02:09:42)] active: 

[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:337 


02:10:27 -- Waiting for model...
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:277 	App: opensearch-main - Units - conditions unmet.
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:278 
	app: opensearch active -- message: None
		opensearch-main-0.13e* -- (10.161.222.32) -- [idle (since: 02:09:42)] active: 

[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:337 


02:10:37 -- Waiting for model...
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:277 	App: opensearch-main - Units - conditions unmet.
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:278 
	app: opensearch active -- message: None
		opensearch-main-0.13e* -- (10.161.222.32) -- [idle (since: 02:09:42)] active: 

[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:337 


02:10:49 -- Waiting for model...
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:277 	App: opensearch-main - Units - conditions unmet.
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:278 
	app: opensearch active -- message: None
		opensearch-main-0.13e* -- (10.161.222.32) -- [idle (since: 02:09:42)] active: 

[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:337 


02:10:59 -- Waiting for model...
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:277 	App: opensearch-data - Units - conditions unmet.
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:278 
	app: opensearch active -- message: None
		opensearch-data-0.ad9  -- (10.161.222.64) -- [idle (since: 02:10:58)] active: 
		opensearch-data-1.ad9* -- (10.161.222.150) -- [idle (since: 02:10:59)] active: 

[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:337 


02:11:12 -- Waiting for model...
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:277 	App: opensearch-data - Units - conditions unmet.
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:278 
	app: opensearch active -- message: None
		opensearch-data-0.ad9  -- (10.161.222.64) -- [idle (since: 02:10:58)] active: 
		opensearch-data-1.ad9* -- (10.161.222.150) -- [idle (since: 02:10:59)] active: 

[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:337 


02:11:24 -- Waiting for model...
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:277 	App: opensearch-data - Units - conditions unmet.
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:278 
	app: opensearch active -- message: None
		opensearch-data-0.ad9  -- (10.161.222.64) -- [idle (since: 02:10:58)] active: 
		opensearch-data-1.ad9* -- (10.161.222.150) -- [idle (since: 02:10:59)] active: 

[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:337 


02:11:36 -- Waiting for model...
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:277 	App: opensearch-data - Units - conditions unmet.
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:278 
	app: opensearch active -- message: None
		opensearch-data-0.ad9  -- (10.161.222.64) -- [idle (since: 02:10:58)] active: 
		opensearch-data-1.ad9* -- (10.161.222.150) -- [idle (since: 02:10:59)] active: 

[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:337 


02:11:48 -- Waiting for model...
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:277 	App: opensearch-data - Units - conditions unmet.
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:278 
	app: opensearch active -- message: None
		opensearch-data-0.ad9  -- (10.161.222.64) -- [idle (since: 02:10:58)] active: 
		opensearch-data-1.ad9* -- (10.161.222.150) -- [idle (since: 02:10:59)] active: 

[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:337 


02:12:00 -- Waiting for model...
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:277 	App: opensearch-data - Units - conditions unmet.
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:278 
	app: opensearch active -- message: None
		opensearch-data-0.ad9  -- (10.161.222.64) -- [idle (since: 02:10:58)] active: 
		opensearch-data-1.ad9* -- (10.161.222.150) -- [idle (since: 02:10:59)] active: 

[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:337 


02:12:13 -- Waiting for model...
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:277 	App: opensearch-failover - Units - conditions unmet.
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:278 
	app: opensearch active -- message: None
		opensearch-failover-0.dd2* -- (10.161.222.138) -- [idle (since: 02:11:04)] active: 

[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:337 


02:12:26 -- Waiting for model...
[32mINFO    [0m integration.helpers_deployments:helpers_deployments.py:348 02:12:28 -- Waiting for model: complete.



[32mINFO    [0m integration.helpers:helpers.py:367 Calling: GET -- https://10.161.222.32:9200/_nodes
[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Model status:

Model  Controller           Cloud/Region         Version  SLA          Timestamp
test   localhost-localhost  localhost/localhost  3.5.3    unsupported  02:12:32Z

App                       Version  Status  Scale  Charm                     Channel        Rev  Exposed  Message
opensearch-data                    active      2  opensearch                                 0  no       
opensearch-failover                active      1  opensearch                                 2  no       
opensearch-main                    active      1  opensearch                                 1  no       
self-signed-certificates           active      1  self-signed-certificates  latest/stable  155  no       

Unit                         Workload  Agent  Machine  Public address  Ports     Message
opensearch-data/0            active    idle   3        10.161.222.64   9200/tcp  
opensearch-data/1*           active    idle   4        10.161.222.150  9200/tcp  
opensearch-failover/0*       active    idle   2        10.161.222.138  9200/tcp  
opensearch-main/0*           active    idle   1        10.161.222.32   9200/tcp  
self-signed-certificates/0*  active    idle   0        10.161.222.106            

Machine  State    Address         Inst id        Base          AZ  Message
0        started  10.161.222.106  juju-69157d-0  ubuntu@22.04      Running
1        started  10.161.222.32   juju-69157d-1  ubuntu@22.04      Running
2        started  10.161.222.138  juju-69157d-2  ubuntu@22.04      Running
3        started  10.161.222.64   juju-69157d-3  ubuntu@22.04      Running
4        started  10.161.222.150  juju-69157d-4  ubuntu@22.04      Running

[32mINFO    [0m pytest_operator.plugin:plugin.py:868 Juju error logs:

machine-0: 01:55:56 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 01:55:56 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-self-signed-certificates-0: 01:55:56 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-2: 01:56:24 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 01:56:24 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-opensearch-failover-0: 01:56:24 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-4: 01:56:46 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-4: 01:56:46 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-opensearch-data-1: 01:56:46 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-1: 01:56:47 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 01:56:47 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-opensearch-main-0: 01:56:47 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-3: 01:58:05 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-3: 01:58:05 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-opensearch-data-0: 01:58:06 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-opensearch-main-0: 02:03:07 ERROR unit.opensearch-main/0.juju-log certificates:9: err:  / out: keytool error: java.lang.Exception: Keystore file does not exist: /var/snap/opensearch/current/etc/opensearch/certificates/ca.p12

unit-opensearch-main-0: 02:04:54 ERROR unit.opensearch-main/0.juju-log peer-cluster-orchestrator:12: Cannot connect to the OpenSearch server...
unit-opensearch-main-0: 02:04:54 ERROR unit.opensearch-main/0.juju-log peer-cluster-orchestrator:12: Cannot connect to the OpenSearch server...
unit-opensearch-main-0: 02:04:54 ERROR unit.opensearch-main/0.juju-log peer-cluster-orchestrator:12: Cannot connect to the OpenSearch server...
unit-opensearch-main-0: 02:04:57 ERROR unit.opensearch-main/0.juju-log peer-cluster-orchestrator:12: Cannot connect to the OpenSearch server...
unit-opensearch-main-0: 02:05:00 ERROR unit.opensearch-main/0.juju-log peer-cluster-orchestrator:12: Cannot connect to the OpenSearch server...
unit-opensearch-main-0: 02:05:03 ERROR unit.opensearch-main/0.juju-log peer-cluster-orchestrator:12: Cannot connect to the OpenSearch server...
unit-opensearch-main-0: 02:05:06 ERROR unit.opensearch-main/0.juju-log peer-cluster-orchestrator:12: Cannot connect to the OpenSearch server...
unit-opensearch-data-0: 02:05:30 ERROR unit.opensearch-data/0.juju-log certificates:11: err:  / out: keytool error: java.lang.Exception: Keystore file does not exist: /var/snap/opensearch/current/etc/opensearch/certificates/ca.p12

unit-opensearch-data-1: 02:05:31 ERROR unit.opensearch-data/1.juju-log certificates:11: err:  / out: keytool error: java.lang.Exception: Keystore file does not exist: /var/snap/opensearch/current/etc/opensearch/certificates/ca.p12

unit-opensearch-data-0: 02:05:35 ERROR unit.opensearch-data/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-data-1: 02:05:35 ERROR unit.opensearch-data/1.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-data-1: 02:05:36 ERROR unit.opensearch-data/1.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-data-0: 02:05:36 ERROR unit.opensearch-data/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-data-1: 02:05:36 ERROR unit.opensearch-data/1.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-data-0: 02:05:37 ERROR unit.opensearch-data/0.juju-log opensearch-peers:5: Cannot connect to the OpenSearch server...
unit-opensearch-data-0: 02:05:39 ERROR unit.opensearch-data/0.juju-log peer-cluster:12: Cannot connect to the OpenSearch server...
unit-opensearch-data-1: 02:05:39 ERROR unit.opensearch-data/1.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-data-1: 02:05:42 ERROR unit.opensearch-data/1.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-data-1: 02:05:45 ERROR unit.opensearch-data/1.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-data-1: 02:05:48 ERROR unit.opensearch-data/1.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-data-0: 02:05:56 ERROR unit.opensearch-data/0.juju-log opensearch-peers:5: Cannot connect to the OpenSearch server...
unit-opensearch-data-0: 02:05:58 ERROR unit.opensearch-data/0.juju-log node-lock-fallback:7: Cannot connect to the OpenSearch server...
unit-opensearch-data-0: 02:06:02 ERROR unit.opensearch-data/0.juju-log node-lock-fallback:7: Cannot connect to the OpenSearch server...
unit-opensearch-data-0: 02:06:03 ERROR unit.opensearch-data/0.juju-log node-lock-fallback:7: Error creating OpenSearch lock document
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-data-0/charm/lib/charms/opensearch/v0/opensearch_distro.py", line 318, in request
    resp = call(urls)
  File "/var/lib/juju/agents/unit-opensearch-data-0/charm/lib/charms/opensearch/v0/opensearch_distro.py", line 256, in call
    for attempt in Retrying(
  File "/var/lib/juju/agents/unit-opensearch-data-0/charm/venv/tenacity/__init__.py", line 443, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/var/lib/juju/agents/unit-opensearch-data-0/charm/venv/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
  File "/var/lib/juju/agents/unit-opensearch-data-0/charm/venv/tenacity/__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
  File "/var/lib/juju/agents/unit-opensearch-data-0/charm/venv/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/var/lib/juju/agents/unit-opensearch-data-0/charm/lib/charms/opensearch/v0/opensearch_distro.py", line 289, in call
    response.raise_for_status()
  File "/var/lib/juju/agents/unit-opensearch-data-0/charm/venv/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://10.161.222.32:9200/.charm_node_lock/_create/0?refresh=true&wait_for_active_shards=all

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-opensearch-data-0/charm/lib/charms/opensearch/v0/opensearch_locking.py", line 304, in acquired
    response = self._opensearch.request(
  File "/var/lib/juju/agents/unit-opensearch-data-0/charm/lib/charms/opensearch/v0/opensearch_distro.py", line 334, in request
    raise OpenSearchHttpError(
charms.opensearch.v0.opensearch_exceptions.OpenSearchHttpError: HTTP error self.response_code=503
self.response_body={'error': {'root_cause': [{'type': 'security_exception', 'reason': 'OpenSearch Security not initialized for indices:admin/mapping/auto_put'}], 'type': 'security_exception', 'reason': 'OpenSearch Security not initialized for indices:admin/mapping/auto_put'}, 'status': 503}
unit-opensearch-data-0: 02:06:07 ERROR unit.opensearch-data/0.juju-log opensearch-peers:5: Cannot connect to the OpenSearch server...
unit-opensearch-data-0: 02:06:10 ERROR unit.opensearch-data/0.juju-log opensearch-peers:5: Cannot connect to the OpenSearch server...
unit-opensearch-failover-0: 02:10:17 ERROR unit.opensearch-failover/0.juju-log certificates:10: err:  / out: keytool error: java.lang.Exception: Keystore file does not exist: /var/snap/opensearch/current/etc/opensearch/certificates/ca.p12

unit-opensearch-failover-0: 02:10:23 ERROR unit.opensearch-failover/0.juju-log Cannot connect to the OpenSearch server...
unit-opensearch-failover-0: 02:10:26 ERROR unit.opensearch-failover/0.juju-log Cannot connect to the OpenSearch server...

[32mINFO    [0m pytest_operator.plugin:plugin.py:947 Forgetting model main...