[32mINFO    [0m integration.ha.test_backups:test_backups.py:490 Remove s3-credentials relation
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  main/0 [idle] active: 
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  main/0 [idle] active: 
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  main/0 [idle] active: 
[32mINFO    [0m integration.ha.test_backups:test_backups.py:502 Re-add s3-credentials relation
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  main/0 [idle] active: 
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  main/0 [executing] maintenance: Configuring backup service...
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  main/0 [idle] active: 
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  main/0 [idle] active: 
[32mINFO    [0m integration.ha.test_backups:test_backups.py:511 Syncing credentials for microceph
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  main/0 [idle] active: 
  s3-integrator/0 [idle] active: 
[32mINFO    [0m integration.helpers:helpers.py:347 Calling: GET -- https://10.19.228.51:9200/_recovery?human
[32mINFO    [0m integration.ha.helpers:helpers.py:247 Continuous writes result: namespace(max_stored_id=333, count=334, last_expected_id=333)
[32mINFO    [0m integration.helpers:helpers.py:347 Calling: GET -- https://10.19.228.51:9200/series_index/_search_shards
[32mINFO    [0m integration.helpers:helpers.py:347 Calling: POST -- https://10.19.228.51:9200/series_index/_refresh
[32mINFO    [0m integration.helpers:helpers.py:347 Calling: GET -- https://10.19.228.51:9200/series_index/_count
[32mINFO    [0m integration.helpers:helpers.py:347 Calling: GET -- https://10.19.228.51:9200/_recovery?human
[32mINFO    [0m integration.helpers:helpers.py:347 Calling: POST -- https://10.19.228.51:9200/series_index/_refresh
[32mINFO    [0m integration.helpers:helpers.py:347 Calling: GET -- https://10.19.228.51:9200/series_index/_count
[32mINFO    [0m integration.ha.helpers:helpers.py:591 Testing restore for series_index - original count pre-restore: 334, and now, new count: 305
[32mINFO    [0m integration.helpers:helpers.py:347 Calling: POST -- https://10.19.228.51:9200/series_index/_refresh
[32mINFO    [0m integration.helpers:helpers.py:347 Calling: GET -- https://10.19.228.51:9200/series_index/_count
[32mINFO    [0m integration.ha.conftest:conftest.py:39 



The writes have been cleared.




[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Model status:

Model  Controller           Cloud/Region         Version  SLA          Timestamp
test   localhost-localhost  localhost/localhost  3.5.3    unsupported  02:28:56Z

App                       Version  Status  Scale  Charm                     Channel        Rev  Exposed  Message
failover                           active      2  opensearch                                 2  no       
main                               active      1  opensearch                                 0  no       
opensearch                         active      1  opensearch                                 1  no       
s3-integrator                      active      1  s3-integrator             latest/edge     41  no       
self-signed-certificates           active      1  self-signed-certificates  latest/stable  155  no       

Unit                         Workload  Agent  Machine  Public address  Ports     Message
failover/0*                  active    idle   3        10.19.228.61    9200/tcp  
failover/1                   active    idle   4        10.19.228.153   9200/tcp  
main/0*                      active    idle   2        10.19.228.51    9200/tcp  
opensearch/0*                active    idle   5        10.19.228.128   9200/tcp  
s3-integrator/0*             active    idle   0        10.19.228.241             
self-signed-certificates/0*  active    idle   1        10.19.228.47              

Machine  State    Address        Inst id        Base          AZ  Message
0        started  10.19.228.241  juju-f566b7-0  ubuntu@22.04      Running
1        started  10.19.228.47   juju-f566b7-1  ubuntu@22.04      Running
2        started  10.19.228.51   juju-f566b7-2  ubuntu@22.04      Running
3        started  10.19.228.61   juju-f566b7-3  ubuntu@22.04      Running
4        started  10.19.228.153  juju-f566b7-4  ubuntu@22.04      Running
5        started  10.19.228.128  juju-f566b7-5  ubuntu@22.04      Running

[32mINFO    [0m pytest_operator.plugin:plugin.py:868 Juju error logs:

machine-1: 02:16:46 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 02:16:46 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-self-signed-certificates-0: 02:16:46 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-0: 02:16:46 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 02:16:46 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-s3-integrator-0: 02:16:47 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-2: 02:17:05 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 02:17:05 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-main-0: 02:17:05 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-5: 02:17:06 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-5: 02:17:06 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-opensearch-0: 02:17:06 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-3: 02:17:06 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-3: 02:17:06 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-failover-0: 02:17:06 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-4: 02:17:07 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-4: 02:17:07 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-failover-1: 02:17:07 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-failover-1: 02:18:15 ERROR unit.failover/1.juju-log [Errno 111] Connection refused
unit-failover-1: 02:18:16 ERROR unit.failover/1.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-failover-1: 02:18:16 ERROR unit.failover/1.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-main-0: 02:18:17 ERROR unit.main/0.juju-log [Errno 111] Connection refused
unit-failover-1: 02:18:17 ERROR unit.failover/1.juju-log certificates:14: [Errno 111] Connection refused
unit-main-0: 02:18:18 ERROR unit.main/0.juju-log certificates:13: [Errno 111] Connection refused
unit-failover-1: 02:18:18 ERROR unit.failover/1.juju-log certificates:14: [Errno 111] Connection refused
unit-main-0: 02:18:19 ERROR unit.main/0.juju-log certificates:13: [Errno 111] Connection refused
unit-failover-1: 02:18:19 ERROR unit.failover/1.juju-log certificates:14: [Errno 111] Connection refused
unit-main-0: 02:18:19 ERROR unit.main/0.juju-log opensearch-peers:4: [Errno 111] Connection refused
unit-main-0: 02:18:19 ERROR unit.main/0.juju-log opensearch-peers:4: [Errno 111] Connection refused
unit-main-0: 02:18:19 ERROR unit.main/0.juju-log opensearch-peers:4: [Errno 111] Connection refused
unit-main-0: 02:18:19 ERROR unit.main/0.juju-log opensearch-peers:4: [Errno 111] Connection refused
unit-main-0: 02:18:20 ERROR unit.main/0.juju-log upgrade-version-a:6: [Errno 111] Connection refused
unit-main-0: 02:18:21 ERROR unit.main/0.juju-log certificates:13: [Errno 111] Connection refused
unit-main-0: 02:18:24 ERROR unit.main/0.juju-log [Errno 111] Connection refused
unit-failover-1: 02:18:25 ERROR unit.failover/1.juju-log peer-cluster-orchestrator:12: [Errno 111] Connection refused
unit-main-0: 02:18:25 ERROR unit.main/0.juju-log [Errno 111] Connection refused
unit-failover-1: 02:18:25 ERROR unit.failover/1.juju-log peer-cluster-orchestrator:12: [Errno 111] Connection refused
unit-main-0: 02:18:26 ERROR unit.main/0.juju-log [Errno 111] Connection refused
unit-failover-1: 02:18:26 ERROR unit.failover/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-main-0: 02:18:27 ERROR unit.main/0.juju-log peer-cluster-orchestrator:10: [Errno 111] Connection refused
unit-main-0: 02:18:27 ERROR unit.main/0.juju-log peer-cluster-orchestrator:10: [Errno 111] Connection refused
unit-main-0: 02:18:27 ERROR unit.main/0.juju-log peer-cluster-orchestrator:10: Cannot connect to the OpenSearch server...
unit-main-0: 02:18:27 ERROR unit.main/0.juju-log peer-cluster-orchestrator:10: [Errno 111] Connection refused
unit-failover-1: 02:18:27 ERROR unit.failover/1.juju-log node-lock-fallback:1: [Errno 111] Connection refused
unit-main-0: 02:18:28 ERROR unit.main/0.juju-log peer-cluster-orchestrator:10: [Errno 111] Connection refused
unit-main-0: 02:18:28 ERROR unit.main/0.juju-log peer-cluster-orchestrator:10: Cannot connect to the OpenSearch server...
unit-main-0: 02:18:28 ERROR unit.main/0.juju-log peer-cluster-orchestrator:10: [Errno 111] Connection refused
unit-main-0: 02:18:28 ERROR unit.main/0.juju-log peer-cluster-orchestrator:10: Cannot connect to the OpenSearch server...
unit-failover-1: 02:18:28 ERROR unit.failover/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-failover-1: 02:18:29 ERROR unit.failover/1.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-1: 02:18:30 ERROR unit.failover/1.juju-log node-lock-fallback:1: [Errno 111] Connection refused
unit-failover-1: 02:18:31 ERROR unit.failover/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-main-0: 02:18:31 ERROR unit.main/0.juju-log peer-cluster-orchestrator:10: [Errno 111] Connection refused
unit-main-0: 02:18:31 ERROR unit.main/0.juju-log peer-cluster-orchestrator:10: Cannot connect to the OpenSearch server...
unit-failover-1: 02:18:32 ERROR unit.failover/1.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-0: 02:18:33 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-failover-0: 02:18:33 ERROR unit.failover/0.juju-log [Errno 111] Connection refused
unit-failover-1: 02:18:33 ERROR unit.failover/1.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-1: 02:18:33 ERROR unit.failover/1.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-1: 02:18:33 ERROR unit.failover/1.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-1: 02:18:33 ERROR unit.failover/1.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-1: 02:18:33 ERROR unit.failover/1.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-1: 02:18:33 ERROR unit.failover/1.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-1: 02:18:33 ERROR unit.failover/1.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-opensearch-0: 02:18:34 ERROR unit.opensearch/0.juju-log opensearch-peers:9: [Errno 111] Connection refused
unit-opensearch-0: 02:18:34 ERROR unit.opensearch/0.juju-log opensearch-peers:9: [Errno 111] Connection refused
unit-opensearch-0: 02:18:34 ERROR unit.opensearch/0.juju-log opensearch-peers:9: [Errno 111] Connection refused
unit-failover-0: 02:18:34 ERROR unit.failover/0.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-opensearch-0: 02:18:34 ERROR unit.opensearch/0.juju-log opensearch-peers:9: [Errno 111] Connection refused
unit-main-0: 02:18:34 ERROR unit.main/0.juju-log peer-cluster-orchestrator:10: [Errno 111] Connection refused
unit-main-0: 02:18:34 ERROR unit.main/0.juju-log peer-cluster-orchestrator:10: Cannot connect to the OpenSearch server...
unit-failover-1: 02:18:34 ERROR unit.failover/1.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-1: 02:18:34 ERROR unit.failover/1.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-1: 02:18:34 ERROR unit.failover/1.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-opensearch-0: 02:18:34 ERROR unit.opensearch/0.juju-log certificates:15: [Errno 111] Connection refused
unit-failover-0: 02:18:35 ERROR unit.failover/0.juju-log peer-cluster-orchestrator:12: [Errno 111] Connection refused
unit-failover-1: 02:18:35 ERROR unit.failover/1.juju-log certificates:14: [Errno 111] Connection refused
unit-opensearch-0: 02:18:35 ERROR unit.opensearch/0.juju-log peer-cluster:11: [Errno 111] Connection refused
unit-failover-0: 02:18:35 ERROR unit.failover/0.juju-log node-lock-fallback:1: [Errno 111] Connection refused
unit-opensearch-0: 02:18:36 ERROR unit.opensearch/0.juju-log peer-cluster:11: [Errno 111] Connection refused
unit-failover-0: 02:18:36 ERROR unit.failover/0.juju-log certificates:14: [Errno 111] Connection refused
unit-main-0: 02:18:37 ERROR unit.main/0.juju-log peer-cluster-orchestrator:10: [Errno 111] Connection refused
unit-main-0: 02:18:37 ERROR unit.main/0.juju-log peer-cluster-orchestrator:10: Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:18:37 ERROR unit.opensearch/0.juju-log peer-cluster:12: [Errno 111] Connection refused
unit-failover-1: 02:18:38 ERROR unit.failover/1.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:18:38 ERROR unit.opensearch/0.juju-log upgrade-version-a:8: [Errno 111] Connection refused
unit-failover-1: 02:18:38 ERROR unit.failover/1.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:18:39 ERROR unit.opensearch/0.juju-log certificates:15: [Errno 111] Connection refused
unit-failover-0: 02:18:39 ERROR unit.failover/0.juju-log [Errno 111] Connection refused
unit-failover-1: 02:18:39 ERROR unit.failover/1.juju-log peer-cluster-orchestrator:12: [Errno 111] Connection refused
unit-failover-0: 02:18:40 ERROR unit.failover/0.juju-log [Errno 111] Connection refused
unit-failover-1: 02:18:40 ERROR unit.failover/1.juju-log [Errno 111] Connection refused
unit-failover-0: 02:18:41 ERROR unit.failover/0.juju-log certificates:14: [Errno 111] Connection refused
unit-failover-1: 02:18:41 ERROR unit.failover/1.juju-log [Errno 111] Connection refused
unit-failover-0: 02:18:42 ERROR unit.failover/0.juju-log [Errno 111] Connection refused
unit-failover-1: 02:18:42 ERROR unit.failover/1.juju-log certificates:14: [Errno 111] Connection refused
unit-opensearch-0: 02:18:42 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-failover-0: 02:18:42 ERROR unit.failover/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:18:42 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-failover-1: 02:18:43 ERROR unit.failover/1.juju-log [Errno 111] Connection refused
unit-failover-0: 02:18:43 ERROR unit.failover/0.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-0: 02:18:43 ERROR unit.failover/0.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-0: 02:18:43 ERROR unit.failover/0.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-0: 02:18:43 ERROR unit.failover/0.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-opensearch-0: 02:18:43 ERROR unit.opensearch/0.juju-log peer-cluster:12: [Errno 111] Connection refused
unit-failover-1: 02:18:44 ERROR unit.failover/1.juju-log [Errno 111] Connection refused
unit-failover-0: 02:18:44 ERROR unit.failover/0.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-opensearch-0: 02:18:44 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-failover-1: 02:18:44 ERROR unit.failover/1.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-1: 02:18:44 ERROR unit.failover/1.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-1: 02:18:44 ERROR unit.failover/1.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-0: 02:18:45 ERROR unit.failover/0.juju-log node-lock-fallback:1: [Errno 111] Connection refused
unit-opensearch-0: 02:18:45 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-failover-1: 02:18:45 ERROR unit.failover/1.juju-log [Errno 111] Connection refused
unit-failover-0: 02:18:45 ERROR unit.failover/0.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-opensearch-0: 02:18:46 ERROR unit.opensearch/0.juju-log opensearch-peers:9: [Errno 111] Connection refused
unit-opensearch-0: 02:18:46 ERROR unit.opensearch/0.juju-log opensearch-peers:9: [Errno 111] Connection refused
unit-opensearch-0: 02:18:46 ERROR unit.opensearch/0.juju-log opensearch-peers:9: [Errno 111] Connection refused
unit-opensearch-0: 02:18:46 ERROR unit.opensearch/0.juju-log opensearch-peers:9: [Errno 111] Connection refused
unit-failover-1: 02:18:46 ERROR unit.failover/1.juju-log [Errno 111] Connection refused
unit-failover-0: 02:18:46 ERROR unit.failover/0.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-0: 02:18:46 ERROR unit.failover/0.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-0: 02:18:46 ERROR unit.failover/0.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-0: 02:18:46 ERROR unit.failover/0.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-0: 02:18:46 ERROR unit.failover/0.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-0: 02:18:46 ERROR unit.failover/0.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-0: 02:18:46 ERROR unit.failover/0.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-0: 02:18:46 ERROR unit.failover/0.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-0: 02:18:46 ERROR unit.failover/0.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-opensearch-0: 02:18:46 ERROR unit.opensearch/0.juju-log peer-cluster:12: [Errno 111] Connection refused
unit-failover-1: 02:18:47 ERROR unit.failover/1.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-1: 02:18:47 ERROR unit.failover/1.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-1: 02:18:47 ERROR unit.failover/1.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-0: 02:18:47 ERROR unit.failover/0.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-0: 02:18:47 ERROR unit.failover/0.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-0: 02:18:47 ERROR unit.failover/0.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-0: 02:18:47 ERROR unit.failover/0.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-0: 02:18:47 ERROR unit.failover/0.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-opensearch-0: 02:18:47 ERROR unit.opensearch/0.juju-log peer-cluster:12: [Errno 111] Connection refused
unit-failover-1: 02:18:47 ERROR unit.failover/1.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-1: 02:18:48 ERROR unit.failover/1.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-1: 02:18:48 ERROR unit.failover/1.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-1: 02:18:48 ERROR unit.failover/1.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-1: 02:18:48 ERROR unit.failover/1.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-1: 02:18:48 ERROR unit.failover/1.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-1: 02:18:48 ERROR unit.failover/1.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-0: 02:18:48 ERROR unit.failover/0.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-opensearch-0: 02:18:48 ERROR unit.opensearch/0.juju-log peer-cluster:12: [Errno 111] Connection refused
unit-failover-1: 02:18:48 ERROR unit.failover/1.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-failover-0: 02:18:49 ERROR unit.failover/0.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-opensearch-0: 02:18:49 ERROR unit.opensearch/0.juju-log opensearch-peers:9: [Errno 111] Connection refused
unit-opensearch-0: 02:18:49 ERROR unit.opensearch/0.juju-log opensearch-peers:9: [Errno 111] Connection refused
unit-opensearch-0: 02:18:49 ERROR unit.opensearch/0.juju-log opensearch-peers:9: [Errno 111] Connection refused
unit-opensearch-0: 02:18:49 ERROR unit.opensearch/0.juju-log opensearch-peers:9: [Errno 111] Connection refused
unit-failover-1: 02:18:50 ERROR unit.failover/1.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-failover-0: 02:18:50 ERROR unit.failover/0.juju-log certificates:14: [Errno 111] Connection refused
unit-opensearch-0: 02:18:50 ERROR unit.opensearch/0.juju-log peer-cluster:12: [Errno 111] Connection refused
unit-failover-0: 02:18:51 ERROR unit.failover/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:18:51 ERROR unit.opensearch/0.juju-log peer-cluster:12: [Errno 111] Connection refused
unit-failover-0: 02:18:52 ERROR unit.failover/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:18:52 ERROR unit.opensearch/0.juju-log certificates:15: [Errno 111] Connection refused
unit-failover-1: 02:18:52 ERROR unit.failover/1.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-failover-0: 02:18:52 ERROR unit.failover/0.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-opensearch-0: 02:18:53 ERROR unit.opensearch/0.juju-log certificates:15: [Errno 111] Connection refused
unit-failover-1: 02:18:53 ERROR unit.failover/1.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-0: 02:18:53 ERROR unit.failover/0.juju-log [Errno 111] Connection refused
unit-failover-1: 02:18:53 ERROR unit.failover/1.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-1: 02:18:53 ERROR unit.failover/1.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-0: 02:18:54 ERROR unit.failover/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:18:54 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-failover-0: 02:18:55 ERROR unit.failover/0.juju-log peer-cluster-orchestrator:12: [Errno 111] Connection refused
unit-opensearch-0: 02:18:55 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-failover-0: 02:18:56 ERROR unit.failover/0.juju-log peer-cluster-orchestrator:12: [Errno 111] Connection refused
unit-failover-0: 02:18:56 ERROR unit.failover/0.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-0: 02:18:56 ERROR unit.failover/0.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-0: 02:18:56 ERROR unit.failover/0.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-0: 02:18:56 ERROR unit.failover/0.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-0: 02:18:56 ERROR unit.failover/0.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-opensearch-0: 02:18:57 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-failover-0: 02:18:57 ERROR unit.failover/0.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-failover-1: 02:18:58 ERROR unit.failover/1.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-opensearch-0: 02:18:58 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-failover-0: 02:18:58 ERROR unit.failover/0.juju-log upgrade-version-a:2: [Errno 111] Connection refused
unit-failover-0: 02:18:59 ERROR unit.failover/0.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-opensearch-0: 02:18:59 ERROR unit.opensearch/0.juju-log peer-cluster:12: [Errno 111] Connection refused
unit-failover-0: 02:18:59 ERROR unit.failover/0.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-failover-0: 02:18:59 ERROR unit.failover/0.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-failover-0: 02:19:00 ERROR unit.failover/0.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-failover-0: 02:19:00 ERROR unit.failover/0.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-failover-0: 02:19:00 ERROR unit.failover/0.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-failover-0: 02:19:00 ERROR unit.failover/0.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-failover-1: 02:19:01 ERROR unit.failover/1.juju-log [Errno 111] Connection refused
unit-failover-0: 02:19:01 ERROR unit.failover/0.juju-log [Errno 111] Connection refused
unit-failover-1: 02:19:01 ERROR unit.failover/1.juju-log [Errno 111] Connection refused
unit-failover-0: 02:19:01 ERROR unit.failover/0.juju-log [Errno 111] Connection refused
unit-failover-1: 02:19:02 ERROR unit.failover/1.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-1: 02:19:02 ERROR unit.failover/1.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-0: 02:19:02 ERROR unit.failover/0.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-0: 02:19:02 ERROR unit.failover/0.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-1: 02:19:03 ERROR unit.failover/1.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-1: 02:19:03 ERROR unit.failover/1.juju-log opensearch-peers:3: Cannot connect to the OpenSearch server...
unit-failover-0: 02:19:03 ERROR unit.failover/0.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-1: 02:19:03 ERROR unit.failover/1.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-0: 02:19:03 ERROR unit.failover/0.juju-log opensearch-peers:3: Cannot connect to the OpenSearch server...
unit-failover-0: 02:19:03 ERROR unit.failover/0.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-0: 02:19:03 ERROR unit.failover/0.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-1: 02:19:03 ERROR unit.failover/1.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-1: 02:19:03 ERROR unit.failover/1.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-0: 02:19:03 ERROR unit.failover/0.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-1: 02:19:03 ERROR unit.failover/1.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-0: 02:19:03 ERROR unit.failover/0.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-1: 02:19:03 ERROR unit.failover/1.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-0: 02:19:03 ERROR unit.failover/0.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-1: 02:19:03 ERROR unit.failover/1.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-0: 02:19:03 ERROR unit.failover/0.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-1: 02:19:03 ERROR unit.failover/1.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-0: 02:19:03 ERROR unit.failover/0.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-1: 02:19:03 ERROR unit.failover/1.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-0: 02:19:03 ERROR unit.failover/0.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-0: 02:19:03 ERROR unit.failover/0.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-1: 02:19:03 ERROR unit.failover/1.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-1: 02:19:03 ERROR unit.failover/1.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-0: 02:19:03 ERROR unit.failover/0.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-1: 02:19:03 ERROR unit.failover/1.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-0: 02:19:04 ERROR unit.failover/0.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-0: 02:19:04 ERROR unit.failover/0.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-0: 02:19:04 ERROR unit.failover/0.juju-log opensearch-peers:3: Cannot connect to the OpenSearch server...
unit-failover-0: 02:19:04 ERROR unit.failover/0.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-1: 02:19:04 ERROR unit.failover/1.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-failover-1: 02:19:04 ERROR unit.failover/1.juju-log peer-cluster:10: Cannot connect to the OpenSearch server...
unit-failover-1: 02:19:04 ERROR unit.failover/1.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-failover-1: 02:19:04 ERROR unit.failover/1.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-failover-1: 02:19:05 ERROR unit.failover/1.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-failover-1: 02:19:05 ERROR unit.failover/1.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-failover-1: 02:19:05 ERROR unit.failover/1.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-failover-1: 02:19:05 ERROR unit.failover/1.juju-log peer-cluster:10: Cannot connect to the OpenSearch server...
unit-failover-1: 02:19:05 ERROR unit.failover/1.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-failover-1: 02:19:06 ERROR unit.failover/1.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-failover-1: 02:19:06 ERROR unit.failover/1.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-failover-1: 02:19:06 ERROR unit.failover/1.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-failover-1: 02:19:07 ERROR unit.failover/1.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-failover-1: 02:19:07 ERROR unit.failover/1.juju-log peer-cluster:10: Cannot connect to the OpenSearch server...
unit-failover-1: 02:19:07 ERROR unit.failover/1.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-failover-1: 02:19:07 ERROR unit.failover/1.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-failover-1: 02:19:07 ERROR unit.failover/1.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-failover-1: 02:19:07 ERROR unit.failover/1.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-failover-0: 02:19:07 ERROR unit.failover/0.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-opensearch-0: 02:19:08 ERROR unit.opensearch/0.juju-log peer-cluster:11: [Errno 111] Connection refused
unit-opensearch-0: 02:19:09 ERROR unit.opensearch/0.juju-log opensearch-peers:9: [Errno 111] Connection refused
unit-opensearch-0: 02:19:09 ERROR unit.opensearch/0.juju-log opensearch-peers:9: [Errno 111] Connection refused
unit-opensearch-0: 02:19:09 ERROR unit.opensearch/0.juju-log opensearch-peers:9: [Errno 111] Connection refused
unit-opensearch-0: 02:19:09 ERROR unit.opensearch/0.juju-log opensearch-peers:9: [Errno 111] Connection refused
unit-failover-0: 02:19:10 ERROR unit.failover/0.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-0: 02:19:13 ERROR unit.failover/0.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-0: 02:19:17 ERROR unit.failover/0.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-0: 02:19:17 ERROR unit.failover/0.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-1: 02:19:18 ERROR unit.failover/1.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-opensearch-0: 02:19:18 ERROR unit.opensearch/0.juju-log peer-cluster:12: [Errno 111] Connection refused
unit-failover-1: 02:19:18 ERROR unit.failover/1.juju-log opensearch-peers:3: Cannot connect to the OpenSearch server...
unit-failover-1: 02:19:18 ERROR unit.failover/1.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-0: 02:19:18 ERROR unit.failover/0.juju-log [Errno 111] Connection refused
unit-failover-1: 02:19:18 ERROR unit.failover/1.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-0: 02:19:18 ERROR unit.failover/0.juju-log [Errno 111] Connection refused
unit-failover-0: 02:19:18 ERROR unit.failover/0.juju-log [Errno 111] Connection refused
unit-failover-1: 02:19:18 ERROR unit.failover/1.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-0: 02:19:19 ERROR unit.failover/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:19:19 ERROR unit.opensearch/0.juju-log opensearch-peers:9: [Errno 111] Connection refused
unit-opensearch-0: 02:19:19 ERROR unit.opensearch/0.juju-log opensearch-peers:9: [Errno 111] Connection refused
unit-opensearch-0: 02:19:19 ERROR unit.opensearch/0.juju-log opensearch-peers:9: [Errno 111] Connection refused
unit-opensearch-0: 02:19:19 ERROR unit.opensearch/0.juju-log opensearch-peers:9: [Errno 111] Connection refused
unit-failover-0: 02:19:19 ERROR unit.failover/0.juju-log [Errno 111] Connection refused
unit-failover-1: 02:19:19 ERROR unit.failover/1.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-1: 02:19:20 ERROR unit.failover/1.juju-log opensearch-peers:3: Cannot connect to the OpenSearch server...
unit-failover-1: 02:19:20 ERROR unit.failover/1.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-1: 02:19:20 ERROR unit.failover/1.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-1: 02:19:20 ERROR unit.failover/1.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-1: 02:19:20 ERROR unit.failover/1.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-1: 02:19:20 ERROR unit.failover/1.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-1: 02:19:20 ERROR unit.failover/1.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-opensearch-0: 02:19:20 ERROR unit.opensearch/0.juju-log peer-cluster:12: [Errno 111] Connection refused
unit-failover-1: 02:19:20 ERROR unit.failover/1.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-0: 02:19:21 ERROR unit.failover/0.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-0: 02:19:21 ERROR unit.failover/0.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-1: 02:19:21 ERROR unit.failover/1.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-1: 02:19:21 ERROR unit.failover/1.juju-log opensearch-peers:3: Cannot connect to the OpenSearch server...
unit-failover-1: 02:19:21 ERROR unit.failover/1.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-opensearch-0: 02:19:22 ERROR unit.opensearch/0.juju-log peer-cluster:12: [Errno 111] Connection refused
unit-failover-0: 02:19:22 ERROR unit.failover/0.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-0: 02:19:22 ERROR unit.failover/0.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-0: 02:19:22 ERROR unit.failover/0.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-0: 02:19:22 ERROR unit.failover/0.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-0: 02:19:23 ERROR unit.failover/0.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-opensearch-0: 02:19:23 ERROR unit.opensearch/0.juju-log peer-cluster:12: [Errno 111] Connection refused
unit-failover-0: 02:19:24 ERROR unit.failover/0.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-opensearch-0: 02:19:24 ERROR unit.opensearch/0.juju-log opensearch-peers:9: [Errno 111] Connection refused
unit-opensearch-0: 02:19:24 ERROR unit.opensearch/0.juju-log opensearch-peers:9: [Errno 111] Connection refused
unit-opensearch-0: 02:19:24 ERROR unit.opensearch/0.juju-log opensearch-peers:9: [Errno 111] Connection refused
unit-opensearch-0: 02:19:24 ERROR unit.opensearch/0.juju-log opensearch-peers:9: [Errno 111] Connection refused
unit-failover-0: 02:19:24 ERROR unit.failover/0.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-failover-1: 02:19:24 ERROR unit.failover/1.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-0: 02:19:25 ERROR unit.failover/0.juju-log peer-cluster:10: [Errno 111] Connection refused
unit-failover-0: 02:19:26 ERROR unit.failover/0.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-0: 02:19:26 ERROR unit.failover/0.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-0: 02:19:26 ERROR unit.failover/0.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-opensearch-0: 02:19:27 ERROR unit.opensearch/0.juju-log peer-cluster:12: [Errno 111] Connection refused
unit-failover-1: 02:19:27 ERROR unit.failover/1.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-failover-1: 02:19:30 ERROR unit.failover/1.juju-log opensearch-peers:3: [Errno 111] Connection refused
unit-opensearch-0: 02:19:38 ERROR unit.opensearch/0.juju-log peer-cluster:12: [Errno 111] Connection refused
unit-opensearch-0: 02:19:38 ERROR unit.opensearch/0.juju-log peer-cluster:12: [Errno 111] Connection refused
unit-opensearch-0: 02:19:39 ERROR unit.opensearch/0.juju-log peer-cluster:12: [Errno 111] Connection refused
unit-opensearch-0: 02:19:39 ERROR unit.opensearch/0.juju-log peer-cluster:12: [Errno 111] Connection refused
unit-opensearch-0: 02:19:40 ERROR unit.opensearch/0.juju-log [Errno 111] Connection refused
unit-opensearch-0: 02:19:41 ERROR unit.opensearch/0.juju-log opensearch-peers:9: [Errno 111] Connection refused
unit-opensearch-0: 02:19:42 ERROR unit.opensearch/0.juju-log opensearch-peers:9: [Errno 111] Connection refused
unit-opensearch-0: 02:19:42 ERROR unit.opensearch/0.juju-log opensearch-peers:9: Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:19:42 ERROR unit.opensearch/0.juju-log opensearch-peers:9: [Errno 111] Connection refused
unit-opensearch-0: 02:19:42 ERROR unit.opensearch/0.juju-log opensearch-peers:9: [Errno 111] Connection refused
unit-opensearch-0: 02:19:42 ERROR unit.opensearch/0.juju-log opensearch-peers:9: [Errno 111] Connection refused
unit-opensearch-0: 02:19:42 ERROR unit.opensearch/0.juju-log opensearch-peers:9: [Errno 111] Connection refused
unit-opensearch-0: 02:19:43 ERROR unit.opensearch/0.juju-log opensearch-peers:9: [Errno 111] Connection refused
unit-opensearch-0: 02:19:43 ERROR unit.opensearch/0.juju-log opensearch-peers:9: [Errno 111] Connection refused
unit-opensearch-0: 02:19:44 ERROR unit.opensearch/0.juju-log opensearch-peers:9: [Errno 111] Connection refused
unit-opensearch-0: 02:19:44 ERROR unit.opensearch/0.juju-log opensearch-peers:9: Cannot connect to the OpenSearch server...
unit-opensearch-0: 02:19:44 ERROR unit.opensearch/0.juju-log opensearch-peers:9: [Errno 111] Connection refused
unit-opensearch-0: 02:19:47 ERROR unit.opensearch/0.juju-log opensearch-peers:9: [Errno 111] Connection refused
unit-opensearch-0: 02:19:50 ERROR unit.opensearch/0.juju-log opensearch-peers:9: [Errno 111] Connection refused
unit-opensearch-0: 02:19:53 ERROR unit.opensearch/0.juju-log opensearch-peers:9: [Errno 111] Connection refused
unit-main-0: 02:21:36 ERROR unit.main/0.juju-log s3-credentials:16: Plugin repository-s3 missing: ['access-key', 'secret-key']
unit-main-0: 02:21:38 ERROR unit.main/0.juju-log s3-credentials:16: Plugin repository-s3 missing: ['access-key', 'secret-key']
unit-main-0: 02:21:39 ERROR unit.main/0.juju-log s3-credentials:16: Plugin repository-s3 missing: ['access-key', 'secret-key']
unit-main-0: 02:21:48 ERROR unit.main/0.juju-log s3-credentials:16: Request PUT to https://10.19.228.51:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'http://localhost', 'protocol': 'http', 'bucket': 'error', 'base_path': '/', 'region': 'default'}} failed.(Attempts left: 5)
	Error: 500 Server Error: Internal Server Error for url: https://10.19.228.51:9200/_snapshot/s3-repository
unit-main-0: 02:21:49 ERROR unit.main/0.juju-log s3-credentials:16: Request PUT to https://10.19.228.51:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'http://localhost', 'protocol': 'http', 'bucket': 'error', 'base_path': '/', 'region': 'default'}} failed.(Attempts left: 4)
	Error: 500 Server Error: Internal Server Error for url: https://10.19.228.51:9200/_snapshot/s3-repository
unit-main-0: 02:21:51 ERROR unit.main/0.juju-log s3-credentials:16: Request PUT to https://10.19.228.51:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'http://localhost', 'protocol': 'http', 'bucket': 'error', 'base_path': '/', 'region': 'default'}} failed.(Attempts left: 3)
	Error: 500 Server Error: Internal Server Error for url: https://10.19.228.51:9200/_snapshot/s3-repository
unit-main-0: 02:21:52 ERROR unit.main/0.juju-log s3-credentials:16: Request PUT to https://10.19.228.51:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'http://localhost', 'protocol': 'http', 'bucket': 'error', 'base_path': '/', 'region': 'default'}} failed.(Attempts left: 2)
	Error: 500 Server Error: Internal Server Error for url: https://10.19.228.51:9200/_snapshot/s3-repository
unit-main-0: 02:21:53 ERROR unit.main/0.juju-log s3-credentials:16: Request PUT to https://10.19.228.51:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'http://localhost', 'protocol': 'http', 'bucket': 'error', 'base_path': '/', 'region': 'default'}} failed.(Attempts left: 1)
	Error: 500 Server Error: Internal Server Error for url: https://10.19.228.51:9200/_snapshot/s3-repository
unit-main-0: 02:21:55 ERROR unit.main/0.juju-log s3-credentials:16: Failed to setup backup service with state repository s3 is unreachable
unit-main-0: 02:22:04 ERROR unit.main/0.juju-log s3-credentials:16: Request PUT to https://10.19.228.51:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'http://localhost', 'protocol': 'http', 'bucket': 'error', 'base_path': '/', 'region': 'default'}} failed.(Attempts left: 5)
	Error: 500 Server Error: Internal Server Error for url: https://10.19.228.51:9200/_snapshot/s3-repository
unit-main-0: 02:22:05 ERROR unit.main/0.juju-log s3-credentials:16: Request PUT to https://10.19.228.51:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'http://localhost', 'protocol': 'http', 'bucket': 'error', 'base_path': '/', 'region': 'default'}} failed.(Attempts left: 4)
	Error: 500 Server Error: Internal Server Error for url: https://10.19.228.51:9200/_snapshot/s3-repository
unit-main-0: 02:22:06 ERROR unit.main/0.juju-log s3-credentials:16: Request PUT to https://10.19.228.51:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'http://localhost', 'protocol': 'http', 'bucket': 'error', 'base_path': '/', 'region': 'default'}} failed.(Attempts left: 3)
	Error: 500 Server Error: Internal Server Error for url: https://10.19.228.51:9200/_snapshot/s3-repository
unit-main-0: 02:22:08 ERROR unit.main/0.juju-log s3-credentials:16: Request PUT to https://10.19.228.51:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'http://localhost', 'protocol': 'http', 'bucket': 'error', 'base_path': '/', 'region': 'default'}} failed.(Attempts left: 2)
	Error: 500 Server Error: Internal Server Error for url: https://10.19.228.51:9200/_snapshot/s3-repository
unit-main-0: 02:22:09 ERROR unit.main/0.juju-log s3-credentials:16: Request PUT to https://10.19.228.51:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'http://localhost', 'protocol': 'http', 'bucket': 'error', 'base_path': '/', 'region': 'default'}} failed.(Attempts left: 1)
	Error: 500 Server Error: Internal Server Error for url: https://10.19.228.51:9200/_snapshot/s3-repository
unit-main-0: 02:22:10 ERROR unit.main/0.juju-log s3-credentials:16: Failed to setup backup service with state repository s3 is unreachable
unit-main-0: 02:22:22 ERROR unit.main/0.juju-log s3-credentials:16: Request PUT to https://10.19.228.51:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'http://localhost', 'protocol': 'http', 'bucket': 'error', 'base_path': '/', 'region': 'default'}} failed.(Attempts left: 5)
	Error: 500 Server Error: Internal Server Error for url: https://10.19.228.51:9200/_snapshot/s3-repository
unit-main-0: 02:22:23 ERROR unit.main/0.juju-log s3-credentials:16: Request PUT to https://10.19.228.51:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'http://localhost', 'protocol': 'http', 'bucket': 'error', 'base_path': '/', 'region': 'default'}} failed.(Attempts left: 4)
	Error: 500 Server Error: Internal Server Error for url: https://10.19.228.51:9200/_snapshot/s3-repository
unit-main-0: 02:22:25 ERROR unit.main/0.juju-log s3-credentials:16: Request PUT to https://10.19.228.51:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'http://localhost', 'protocol': 'http', 'bucket': 'error', 'base_path': '/', 'region': 'default'}} failed.(Attempts left: 3)
	Error: 500 Server Error: Internal Server Error for url: https://10.19.228.51:9200/_snapshot/s3-repository
unit-main-0: 02:22:26 ERROR unit.main/0.juju-log s3-credentials:16: Request PUT to https://10.19.228.51:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'http://localhost', 'protocol': 'http', 'bucket': 'error', 'base_path': '/', 'region': 'default'}} failed.(Attempts left: 2)
	Error: 500 Server Error: Internal Server Error for url: https://10.19.228.51:9200/_snapshot/s3-repository
unit-main-0: 02:22:27 ERROR unit.main/0.juju-log s3-credentials:16: Request PUT to https://10.19.228.51:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'http://localhost', 'protocol': 'http', 'bucket': 'error', 'base_path': '/', 'region': 'default'}} failed.(Attempts left: 1)
	Error: 500 Server Error: Internal Server Error for url: https://10.19.228.51:9200/_snapshot/s3-repository
unit-main-0: 02:22:29 ERROR unit.main/0.juju-log s3-credentials:16: Failed to setup backup service with state repository s3 is unreachable
unit-main-0: 02:22:43 ERROR unit.main/0.juju-log s3-credentials:16: Request PUT to https://10.19.228.51:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'http://10.145.253.186', 'protocol': 'http', 'bucket': 'testbucket', 'base_path': 'opensearch/49d73315-d4c1-410e-89d6-e629503bce7c', 'region': 'default'}} failed.(Attempts left: 5)
	Error: 500 Server Error: Internal Server Error for url: https://10.19.228.51:9200/_snapshot/s3-repository
unit-main-0: 02:22:44 ERROR unit.main/0.juju-log s3-credentials:16: Request PUT to https://10.19.228.51:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'http://10.145.253.186', 'protocol': 'http', 'bucket': 'testbucket', 'base_path': 'opensearch/49d73315-d4c1-410e-89d6-e629503bce7c', 'region': 'default'}} failed.(Attempts left: 4)
	Error: 500 Server Error: Internal Server Error for url: https://10.19.228.51:9200/_snapshot/s3-repository
unit-main-0: 02:22:45 ERROR unit.main/0.juju-log s3-credentials:16: Request PUT to https://10.19.228.51:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'http://10.145.253.186', 'protocol': 'http', 'bucket': 'testbucket', 'base_path': 'opensearch/49d73315-d4c1-410e-89d6-e629503bce7c', 'region': 'default'}} failed.(Attempts left: 3)
	Error: 500 Server Error: Internal Server Error for url: https://10.19.228.51:9200/_snapshot/s3-repository
unit-main-0: 02:22:47 ERROR unit.main/0.juju-log s3-credentials:16: Request PUT to https://10.19.228.51:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'http://10.145.253.186', 'protocol': 'http', 'bucket': 'testbucket', 'base_path': 'opensearch/49d73315-d4c1-410e-89d6-e629503bce7c', 'region': 'default'}} failed.(Attempts left: 2)
	Error: 500 Server Error: Internal Server Error for url: https://10.19.228.51:9200/_snapshot/s3-repository
unit-main-0: 02:22:48 ERROR unit.main/0.juju-log s3-credentials:16: Request PUT to https://10.19.228.51:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'http://10.145.253.186', 'protocol': 'http', 'bucket': 'testbucket', 'base_path': 'opensearch/49d73315-d4c1-410e-89d6-e629503bce7c', 'region': 'default'}} failed.(Attempts left: 1)
	Error: 500 Server Error: Internal Server Error for url: https://10.19.228.51:9200/_snapshot/s3-repository
unit-failover-0: 02:22:54 ERROR unit.failover/0.juju-log /snap/opensearch/current/usr/share/opensearch/bin/opensearch-keystore remove s3.client.default.access_key:
 Stderr: warning: no-jdk distributions that do not bundle a JDK are deprecated and will be removed in a future release
ERROR: Setting [s3.client.default.access_key] does not exist in the keystore.

 Stdout: 
unit-opensearch-0: 02:22:54 ERROR unit.opensearch/0.juju-log /snap/opensearch/current/usr/share/opensearch/bin/opensearch-keystore remove s3.client.default.access_key:
 Stderr: warning: no-jdk distributions that do not bundle a JDK are deprecated and will be removed in a future release
ERROR: Setting [s3.client.default.access_key] does not exist in the keystore.

 Stdout: 
unit-failover-0: 02:22:56 ERROR unit.failover/0.juju-log /snap/opensearch/current/usr/share/opensearch/bin/opensearch-keystore remove s3.client.default.access_key:
 Stderr: warning: no-jdk distributions that do not bundle a JDK are deprecated and will be removed in a future release
ERROR: Setting [s3.client.default.access_key] does not exist in the keystore.

 Stdout: 
unit-opensearch-0: 02:22:56 ERROR unit.opensearch/0.juju-log /snap/opensearch/current/usr/share/opensearch/bin/opensearch-keystore remove s3.client.default.access_key:
 Stderr: warning: no-jdk distributions that do not bundle a JDK are deprecated and will be removed in a future release
ERROR: Setting [s3.client.default.access_key] does not exist in the keystore.

 Stdout: 
unit-failover-0: 02:22:57 ERROR unit.failover/0.juju-log /snap/opensearch/current/usr/share/opensearch/bin/opensearch-keystore remove s3.client.default.access_key:
 Stderr: warning: no-jdk distributions that do not bundle a JDK are deprecated and will be removed in a future release
ERROR: Setting [s3.client.default.access_key] does not exist in the keystore.

 Stdout: 
unit-opensearch-0: 02:22:57 ERROR unit.opensearch/0.juju-log /snap/opensearch/current/usr/share/opensearch/bin/opensearch-keystore remove s3.client.default.access_key:
 Stderr: warning: no-jdk distributions that do not bundle a JDK are deprecated and will be removed in a future release
ERROR: Setting [s3.client.default.access_key] does not exist in the keystore.

 Stdout: 
unit-failover-0: 02:22:58 ERROR unit.failover/0.juju-log /snap/opensearch/current/usr/share/opensearch/bin/opensearch-keystore remove s3.client.default.secret_key:
 Stderr: warning: no-jdk distributions that do not bundle a JDK are deprecated and will be removed in a future release
ERROR: Setting [s3.client.default.secret_key] does not exist in the keystore.

 Stdout: 
unit-opensearch-0: 02:22:58 ERROR unit.opensearch/0.juju-log /snap/opensearch/current/usr/share/opensearch/bin/opensearch-keystore remove s3.client.default.secret_key:
 Stderr: warning: no-jdk distributions that do not bundle a JDK are deprecated and will be removed in a future release
ERROR: Setting [s3.client.default.secret_key] does not exist in the keystore.

 Stdout: 
unit-failover-0: 02:23:00 ERROR unit.failover/0.juju-log /snap/opensearch/current/usr/share/opensearch/bin/opensearch-keystore remove s3.client.default.secret_key:
 Stderr: warning: no-jdk distributions that do not bundle a JDK are deprecated and will be removed in a future release
ERROR: Setting [s3.client.default.secret_key] does not exist in the keystore.

 Stdout: 
unit-opensearch-0: 02:23:00 ERROR unit.opensearch/0.juju-log /snap/opensearch/current/usr/share/opensearch/bin/opensearch-keystore remove s3.client.default.secret_key:
 Stderr: warning: no-jdk distributions that do not bundle a JDK are deprecated and will be removed in a future release
ERROR: Setting [s3.client.default.secret_key] does not exist in the keystore.

 Stdout: 
unit-failover-0: 02:23:01 ERROR unit.failover/0.juju-log /snap/opensearch/current/usr/share/opensearch/bin/opensearch-keystore remove s3.client.default.secret_key:
 Stderr: warning: no-jdk distributions that do not bundle a JDK are deprecated and will be removed in a future release
ERROR: Setting [s3.client.default.secret_key] does not exist in the keystore.

 Stdout: 
unit-opensearch-0: 02:23:01 ERROR unit.opensearch/0.juju-log /snap/opensearch/current/usr/share/opensearch/bin/opensearch-keystore remove s3.client.default.secret_key:
 Stderr: warning: no-jdk distributions that do not bundle a JDK are deprecated and will be removed in a future release
ERROR: Setting [s3.client.default.secret_key] does not exist in the keystore.

 Stdout: 
unit-s3-integrator-0: 02:24:25 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: relation scope id "c21a3230-aacf-4984-819d-578bddf566b7:r#16#main": settings c21a3230-aacf-4984-819d-578bddf566b7:r#16#main not found (not found)
unit-main-0: 02:25:52 ERROR unit.main/0.juju-log s3-credentials:19: Request PUT to https://10.19.228.51:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'http://10.145.253.186', 'protocol': 'http', 'bucket': 'testbucket', 'base_path': 'opensearch/49d73315-d4c1-410e-89d6-e629503bce7c', 'region': 'default'}} failed.(Attempts left: 5)
	Error: 500 Server Error: Internal Server Error for url: https://10.19.228.51:9200/_snapshot/s3-repository
unit-main-0: 02:25:53 ERROR unit.main/0.juju-log s3-credentials:19: Request PUT to https://10.19.228.51:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'http://10.145.253.186', 'protocol': 'http', 'bucket': 'testbucket', 'base_path': 'opensearch/49d73315-d4c1-410e-89d6-e629503bce7c', 'region': 'default'}} failed.(Attempts left: 4)
	Error: 500 Server Error: Internal Server Error for url: https://10.19.228.51:9200/_snapshot/s3-repository
unit-main-0: 02:25:54 ERROR unit.main/0.juju-log s3-credentials:19: Request PUT to https://10.19.228.51:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'http://10.145.253.186', 'protocol': 'http', 'bucket': 'testbucket', 'base_path': 'opensearch/49d73315-d4c1-410e-89d6-e629503bce7c', 'region': 'default'}} failed.(Attempts left: 3)
	Error: 500 Server Error: Internal Server Error for url: https://10.19.228.51:9200/_snapshot/s3-repository
unit-main-0: 02:25:55 ERROR unit.main/0.juju-log s3-credentials:19: Request PUT to https://10.19.228.51:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'http://10.145.253.186', 'protocol': 'http', 'bucket': 'testbucket', 'base_path': 'opensearch/49d73315-d4c1-410e-89d6-e629503bce7c', 'region': 'default'}} failed.(Attempts left: 2)
	Error: 500 Server Error: Internal Server Error for url: https://10.19.228.51:9200/_snapshot/s3-repository
unit-main-0: 02:25:57 ERROR unit.main/0.juju-log s3-credentials:19: Request PUT to https://10.19.228.51:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'http://10.145.253.186', 'protocol': 'http', 'bucket': 'testbucket', 'base_path': 'opensearch/49d73315-d4c1-410e-89d6-e629503bce7c', 'region': 'default'}} failed.(Attempts left: 1)
	Error: 500 Server Error: Internal Server Error for url: https://10.19.228.51:9200/_snapshot/s3-repository
unit-main-0: 02:26:07 ERROR unit.main/0.juju-log s3-credentials:19: Request PUT to https://10.19.228.51:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'http://10.145.253.186', 'protocol': 'http', 'bucket': 'testbucket', 'base_path': 'opensearch/49d73315-d4c1-410e-89d6-e629503bce7c', 'region': 'default'}} failed.(Attempts left: 5)
	Error: 500 Server Error: Internal Server Error for url: https://10.19.228.51:9200/_snapshot/s3-repository
unit-main-0: 02:26:08 ERROR unit.main/0.juju-log s3-credentials:19: Request PUT to https://10.19.228.51:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'http://10.145.253.186', 'protocol': 'http', 'bucket': 'testbucket', 'base_path': 'opensearch/49d73315-d4c1-410e-89d6-e629503bce7c', 'region': 'default'}} failed.(Attempts left: 4)
	Error: 500 Server Error: Internal Server Error for url: https://10.19.228.51:9200/_snapshot/s3-repository
unit-main-0: 02:26:10 ERROR unit.main/0.juju-log s3-credentials:19: Request PUT to https://10.19.228.51:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'http://10.145.253.186', 'protocol': 'http', 'bucket': 'testbucket', 'base_path': 'opensearch/49d73315-d4c1-410e-89d6-e629503bce7c', 'region': 'default'}} failed.(Attempts left: 3)
	Error: 500 Server Error: Internal Server Error for url: https://10.19.228.51:9200/_snapshot/s3-repository
unit-main-0: 02:26:11 ERROR unit.main/0.juju-log s3-credentials:19: Request PUT to https://10.19.228.51:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'http://10.145.253.186', 'protocol': 'http', 'bucket': 'testbucket', 'base_path': 'opensearch/49d73315-d4c1-410e-89d6-e629503bce7c', 'region': 'default'}} failed.(Attempts left: 2)
	Error: 500 Server Error: Internal Server Error for url: https://10.19.228.51:9200/_snapshot/s3-repository
unit-main-0: 02:26:12 ERROR unit.main/0.juju-log s3-credentials:19: Request PUT to https://10.19.228.51:9200/_snapshot/s3-repository with payload: {'type': 's3', 'settings': {'endpoint': 'http://10.145.253.186', 'protocol': 'http', 'bucket': 'testbucket', 'base_path': 'opensearch/49d73315-d4c1-410e-89d6-e629503bce7c', 'region': 'default'}} failed.(Attempts left: 1)
	Error: 500 Server Error: Internal Server Error for url: https://10.19.228.51:9200/_snapshot/s3-repository

[32mINFO    [0m pytest_operator.plugin:plugin.py:947 Forgetting model main...
[32mINFO    [0m integration.ha.test_backups:test_backups.py:173 Cleaning backups from cloud buckets